<a href="https://colab.research.google.com/github/sensein/asd-ai-scoping-review/blob/main/scripts/PRISMA_pipeline_Fabio/bib_to_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install bibtexparser

Collecting bibtexparser
  Downloading bibtexparser-1.4.1.tar.gz (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyparsing>=2.0.3 in /usr/local/lib/python3.10/dist-packages (from bibtexparser) (3.1.1)
Building wheels for collected packages: bibtexparser
  Building wheel for bibtexparser (setup.py) ... done
  Created wheel for bibtexparser: filename=bibtexparser-1.4.1-py3-none-any.whl size=43252 sha256=2b60c6d695e9b0549a7b0d17eaf5f2e68ac52437c697088a29d0ea072c8b65b9
  Stored in directory: /root/.cache/pip/wheels/08/c6/c3/56e639fab68d1fdbf13ea147636d9795ccdbd3c1d3178d1332
Successfully built bibtexparser
Installing collected packages: bibtexparser
Successfully installed bibtexparser-1.4.1

In [ ]:
# Mount Google Drive
from google.colab import drive as gdrive
import os
import csv
from bibtexparser.bparser import BibTexParser
import pandas as pd
from collections import OrderedDict

In [ ]:
gdrive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
workspace = "/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)"

In [ ]:
# Folder containing .bib file
bib_folder = f"{workspace}/bib/"

# Output CSV file
output_csv = f"{workspace}/autism.csv"

output_csv_formatted = f"{workspace}/autism_formatted.csv"

In [ ]:
# Set to store all unique fields encountered
all_fields = set()

# List to store all entries
all_entries = []

# Loop through each .bib file in the folder
for bib_file in os.listdir(bib_folder):
    if bib_file.endswith(".bib"):
        bib_path = os.path.join(bib_folder, bib_file)
        print(bib_path)

        # Parse the .bib file
        with open(bib_path, "r", encoding="utf-8") as file:
            parser = BibTexParser()
            parser.ignore_nonstandard_types = False
            bib_data = parser.parse_file(file)

        # Extract and store each entry
        for entry in bib_data.entries:
            entry_dict = {"Key": entry.get("ID")}
            entry_dict.update(entry)
            all_entries.append(entry_dict)
            all_fields.update(entry.keys())  # Update the set of all encountered fields

print(len(all_entries))

# Convert the set of all fields to a sorted list
fieldnames = ["Key"] + sorted(all_fields)

# Write entries to CSV
with open(output_csv, "w", newline="", encoding="utf-8") as csv_file:
    csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    csv_writer.writeheader()
    csv_writer.writerows(all_entries)

print(f"CSV file '{output_csv}' created with {len(all_entries)} entries.")

/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)/bib/acm (2).bib
/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)/bib/acm (3).bib
/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)/bib/acm (4).bib
/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)/bib/acm (5).bib
/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)/bib/acm (6).bib
/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)/bib/acm (7).bib
/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)/bib/acm (8).bib
/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)/bib/acm (9).bib
/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)/bib/acm_3305356.bib
3553
CSV file '/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries/acm_digital_library (new method)/autism.csv' created with 3553 entries.

In [ ]:
df = pd.read_csv(output_csv)
df

,Key,ENTRYTYPE,ID,abstract,address,articleno,author,booktitle,doi,edition,...,note,number,numpages,pages,publisher,series,title,url,volume,year
0,10.1145/2674377.2678271,inproceedings,10.1145/2674377.2678271,In India there is a general lack of informatio...,"New York, NY, USA",NaN,"Gupta, Nakull and Arriaga, Rosa I.",Proceedings of the Fifth ACM Symposium on Comp...,10.1145/2674377.2678271,NaN,...,NaN,NaN,2.0,123–124,Association for Computing Machinery,ACM DEV-5 '14,Tell Me About Autism: Autism Resources for India,https://doi.org/10.1145/2674377.2678271,NaN,2014
1,10.1145/3287098.3287137,inproceedings,10.1145/3287098.3287137,We present an initial qualitative exploration ...,"New York, NY, USA",41.0,"Karusala, Naveena and Kumar, Neha and Arriaga,...",Proceedings of the Tenth International Confere...,10.1145/3287098.3287137,NaN,...,NaN,NaN,5.0,NaN,Association for Computing Machinery,ICTD '19,#autism: Twitter as a Lens to Explore Differen...,https://doi.org/10.1145/3287098.3287137,NaN,2019
2,10.1145/3264631.3264633,article,10.1145/3264631.3264633,People with autism consistently exhibit differ...,"New York, NY, USA",2.0,"Yaneva, Victoria",NaN,10.1145/3264631.3264633,NaN,...,NaN,121,1.0,NaN,Association for Computing Machinery,NaN,Autism and the Web: Using Web-Searching Tasks ...,https://doi.org/10.1145/3264631.3264633,NaN,2018
3,10.1145/3267305.3267648,inproceedings,10.1145/3267305.3267648,"In this paper, a smartphone application ""iTrac...","New York, NY, USA",NaN,"Ishaq, Adeed and Shoaib, Muhammad and Raza, Ha...",Proceedings of the 2018 ACM International Join...,10.1145/3267305.3267648,NaN,...,NaN,NaN,4.0,70–73,Association for Computing Machinery,UbiComp '18,ITrack Application for Autism: Supporting and ...,https://doi.org/10.1145/3267305.3267648,NaN,2018
4,10.1145/3292147.3292208,inproceedings,10.1145/3292147.3292208,Many autism intervention approaches are based ...,"New York, NY, USA",NaN,"Alarcon-Licona, Susana and Loke, Lian and Ahma...",Proceedings of the 30th Australian Conference ...,10.1145/3292147.3292208,NaN,...,NaN,NaN,5.0,58–62,Association for Computing Machinery,OzCHI '18,From Autism Educators to Game Designers: Integ...,https://doi.org/10.1145/3292147.3292208,NaN,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,10.1145/3290607.3311779,inproceedings,10.1145/3290607.3311779,"In this video artwork, the author looks at the...","New York, NY, USA",NaN,"Damiani, Luca M.",Extended Abstracts of the 2019 CHI Conference ...,10.1145/3290607.3311779,NaN,...,NaN,NaN,2.0,1–2,Association for Computing Machinery,CHI EA '19,Hyper Sensorial -- Human Computed Neurodiverge...,https://doi.org/10.1145/3290607.3311779,NaN,2019
3549,10.1145/2967934.2968085,inproceedings,10.1145/2967934.2968085,Neurofeedback training can reduce symptoms rel...,"New York, NY, USA",NaN,"Reinschluessel, Anke V. and Mandryk, Regan L.",Proceedings of the 2016 Annual Symposium on Co...,10.1145/2967934.2968085,NaN,...,NaN,NaN,13.0,186–198,Association for Computing Machinery,CHI PLAY '16,Using Positive or Negative Reinforcement in Ne...,https://doi.org/10.1145/2967934.2968085,NaN,2016
3550,10.1145/2522848.2532191,inproceedings,10.1145/2522848.2532191,"Autism Spectrum Disorders (ASD), often referre...","New York, NY, USA",NaN,"Rajagopalan, Shyam Sundar",Proceedings of the 15th ACM on International C...,10.1145/2522848.2532191,NaN,...,NaN,NaN,4.0,361–364,Association for Computing Machinery,ICMI '13,Computational Behaviour Modelling for Autism D...,https://doi.org/10.1145/2522848.2532191,NaN,2013
3551,10.1145/3511047.3537690,inproceedings,10.1145/3511047.3537690,This paper describes our proposal for enrichin...,"New York, NY, USA",NaN,"Gena, Cristina and Damiano, Rossana and Mattut...",Adjunct Proceedings of the 30th ACM Conference...,10.1145/3511047.3537690,NaN,...,NaN,NaN,4.0,151–154,Association for Computing Machinery,UMAP '22 Adjunct,Ontologies and Open Data for Enriching Persona...,https://doi.org/10.1145/3511047.3537690,NaN,2022
3552,10.1145/3305356,article,10.1145/3305356,NaN,"New York, NY, USA",NaN,"Hudson, William",NaN,10.1145/3305356,NaN,...,NaN,2,5.0,55–59,Association for Computing Machinery,NaN,"Asperger's Syndrome, Autism, and Camouflaging:...",https://doi.org/10.1145/3305356,26.0,2019

In [ ]:
df = df.drop_duplicates(subset=['ID'])
df

,Key,ENTRYTYPE,ID,abstract,address,articleno,author,booktitle,doi,edition,...,note,number,numpages,pages,publisher,series,title,url,volume,year
0,10.1145/2674377.2678271,inproceedings,10.1145/2674377.2678271,In India there is a general lack of informatio...,"New York, NY, USA",NaN,"Gupta, Nakull and Arriaga, Rosa I.",Proceedings of the Fifth ACM Symposium on Comp...,10.1145/2674377.2678271,NaN,...,NaN,NaN,2.0,123–124,Association for Computing Machinery,ACM DEV-5 '14,Tell Me About Autism: Autism Resources for India,https://doi.org/10.1145/2674377.2678271,NaN,2014
1,10.1145/3287098.3287137,inproceedings,10.1145/3287098.3287137,We present an initial qualitative exploration ...,"New York, NY, USA",41.0,"Karusala, Naveena and Kumar, Neha and Arriaga,...",Proceedings of the Tenth International Confere...,10.1145/3287098.3287137,NaN,...,NaN,NaN,5.0,NaN,Association for Computing Machinery,ICTD '19,#autism: Twitter as a Lens to Explore Differen...,https://doi.org/10.1145/3287098.3287137,NaN,2019
2,10.1145/3264631.3264633,article,10.1145/3264631.3264633,People with autism consistently exhibit differ...,"New York, NY, USA",2.0,"Yaneva, Victoria",NaN,10.1145/3264631.3264633,NaN,...,NaN,121,1.0,NaN,Association for Computing Machinery,NaN,Autism and the Web: Using Web-Searching Tasks ...,https://doi.org/10.1145/3264631.3264633,NaN,2018
3,10.1145/3267305.3267648,inproceedings,10.1145/3267305.3267648,"In this paper, a smartphone application ""iTrac...","New York, NY, USA",NaN,"Ishaq, Adeed and Shoaib, Muhammad and Raza, Ha...",Proceedings of the 2018 ACM International Join...,10.1145/3267305.3267648,NaN,...,NaN,NaN,4.0,70–73,Association for Computing Machinery,UbiComp '18,ITrack Application for Autism: Supporting and ...,https://doi.org/10.1145/3267305.3267648,NaN,2018
4,10.1145/3292147.3292208,inproceedings,10.1145/3292147.3292208,Many autism intervention approaches are based ...,"New York, NY, USA",NaN,"Alarcon-Licona, Susana and Loke, Lian and Ahma...",Proceedings of the 30th Australian Conference ...,10.1145/3292147.3292208,NaN,...,NaN,NaN,5.0,58–62,Association for Computing Machinery,OzCHI '18,From Autism Educators to Game Designers: Integ...,https://doi.org/10.1145/3292147.3292208,NaN,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,10.5555/2906831.2906930,inproceedings,10.5555/2906831.2906930,"Guided by soft systems methodology, in an 8-mo...",NaN,NaN,"Lewis, Lundy and Charron, Nancy and Clamp, Chr...",The Eleventh ACM/IEEE International Conference...,NaN,NaN,...,NaN,NaN,2.0,467–468,IEEE Press,HRI '16,Soft Systems Methodology as a Tool to Aid a Pi...,NaN,NaN,2016
1709,10.1145/3441852.3476470,inproceedings,10.1145/3441852.3476470,"Due to the COVID-19 pandemic, essential servic...","New York, NY, USA",38.0,"Thang, Tiffany and Liang, Alice and Choi, Yech...",Proceedings of the 23rd International ACM SIGA...,10.1145/3441852.3476470,NaN,...,NaN,NaN,6.0,NaN,Association for Computing Machinery,ASSETS '21,Providing and Accessing Support During the COV...,https://doi.org/10.1145/3441852.3476470,NaN,2021
1759,10.1145/2557595.2557596,inproceedings,10.1145/2557595.2557596,The Inputs-Outputs interdisciplinary conferenc...,"New York, NY, USA",1.0,"Witchel, Harry J.",Proceedings of the 2013 Inputs-Outputs Confere...,10.1145/2557595.2557596,NaN,...,NaN,NaN,4.0,NaN,Association for Computing Machinery,Inputs-Outputs '13,Engagement: The Inputs and the Outputs: Confer...,https://doi.org/10.1145/2557595.2557596,NaN,2013
3548,10.1145/3290607.3311779,inproceedings,10.1145/3290607.3311779,"In this video artwork, the author looks at the...","New York, NY, USA",NaN,"Damiani, Luca M.",Extended Abstracts of the 2019 CHI Conference ...,10.1145/3290607.3311779,NaN,...,NaN,NaN,2.0,1–2,Association for Computing Machinery,CHI EA '19,Hyper Sensorial -- Human Computed Neurodiverge...,https://doi.org/10.1145/3290607.3311779,NaN,2019
3549,10.1145/2967934.2968085,inproceedings,10.1145/2967934.2968085,Neurofeedback training can reduce symptoms rel...,"New York, NY, USA",NaN,"Reinschluessel, Anke V. and Mandryk, Regan L.",Proceedings of the 2016 Annual Symposium on Co...,10.1145/2967934.2968085,NaN,...,NaN,NaN,13.0,186–198,Association for Computing Machinery,CHI PLAY '16,Using Positive or Negative Reinforcement in Ne...,https://doi.org/10.1145/2967934.2968085,NaN,2016

In [ ]:
# Define a dictionary to map the old column names to the new ones
column_mapping = OrderedDict([
    ('title', 'Title'),
    ('abstract', 'Abstract'),
    ('keywords', 'Keywords'),
    ('doi', 'DOI'),
    ('url', 'URL'),
    ('author', 'Authors'),
    ('booktitle', 'Venue'),
    ('year', 'Year')
])

column_order = ['Title', 'Abstract', 'Keywords', 'DOI', 'URL', 'Authors', 'Venue', 'Year']

# Rename the columns based on the mapping
df.rename(columns=column_mapping, inplace=True)

# List of columns to drop
columns_to_drop = [col for col in df.columns if col not in column_mapping.values()]

# Drop the unwanted columns
df.drop(columns=columns_to_drop, inplace=True)

df = df[column_order]

<ipython-input-10-07cc03d623c8>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns=column_mapping, inplace=True)
<ipython-input-10-07cc03d623c8>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=columns_to_drop, inplace=True)

In [ ]:
df

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year
0,Tell Me About Autism: Autism Resources for India,In India there is a general lack of informatio...,"wiki, community software, tellmeaboutautism, h...",10.1145/2674377.2678271,https://doi.org/10.1145/2674377.2678271,"Gupta, Nakull and Arriaga, Rosa I.",Proceedings of the Fifth ACM Symposium on Comp...,2014
1,#autism: Twitter as a Lens to Explore Differen...,We present an initial qualitative exploration ...,"autism, Twitter, HCI",10.1145/3287098.3287137,https://doi.org/10.1145/3287098.3287137,"Karusala, Naveena and Kumar, Neha and Arriaga,...",Proceedings of the Tenth International Confere...,2019
2,Autism and the Web: Using Web-Searching Tasks ...,People with autism consistently exhibit differ...,NaN,10.1145/3264631.3264633,https://doi.org/10.1145/3264631.3264633,"Yaneva, Victoria",NaN,2018
3,ITrack Application for Autism: Supporting and ...,"In this paper, a smartphone application ""iTrac...","Emergency Support, Learning, Autism, Safety",10.1145/3267305.3267648,https://doi.org/10.1145/3267305.3267648,"Ishaq, Adeed and Shoaib, Muhammad and Raza, Ha...",Proceedings of the 2018 ACM International Join...,2018
4,From Autism Educators to Game Designers: Integ...,Many autism intervention approaches are based ...,"digital technology for special education, game...",10.1145/3292147.3292208,https://doi.org/10.1145/3292147.3292208,"Alarcon-Licona, Susana and Loke, Lian and Ahma...",Proceedings of the 30th Australian Conference ...,2018
...,...,...,...,...,...,...,...,...
1703,Soft Systems Methodology as a Tool to Aid a Pi...,"Guided by soft systems methodology, in an 8-mo...","soft systems, socially assistive robot, soft s...",NaN,NaN,"Lewis, Lundy and Charron, Nancy and Clamp, Chr...",The Eleventh ACM/IEEE International Conference...,2016
1709,Providing and Accessing Support During the COV...,"Due to the COVID-19 pandemic, essential servic...","telehealth, community centers, essential servi...",10.1145/3441852.3476470,https://doi.org/10.1145/3441852.3476470,"Thang, Tiffany and Liang, Alice and Choi, Yech...",Proceedings of the 23rd International ACM SIGA...,2021
1759,Engagement: The Inputs and the Outputs: Confer...,The Inputs-Outputs interdisciplinary conferenc...,"cognitive absorption, interest, motivation, im...",10.1145/2557595.2557596,https://doi.org/10.1145/2557595.2557596,"Witchel, Harry J.",Proceedings of the 2013 Inputs-Outputs Confere...,2013
3548,Hyper Sensorial -- Human Computed Neurodiverge...,"In this video artwork, the author looks at the...","computing, psychology, science, neurodiversity...",10.1145/3290607.3311779,https://doi.org/10.1145/3290607.3311779,"Damiani, Luca M.",Extended Abstracts of the 2019 CHI Conference ...,2019
3549,Using Positive or Negative Reinforcement in Ne...,Neurofeedback training can reduce symptoms rel...,"reinforcement, neurofeedback, games, biofeedback",10.1145/2967934.2968085,https://doi.org/10.1145/2967934.2968085,"Reinschluessel, Anke V. and Mandryk, Regan L.",Proceedings of the 2016 Annual Symposium on Co...,2016

In [ ]:
df.to_csv(output_csv_formatted, index=False)