<a href="https://colab.research.google.com/github/sensein/asd-ai-scoping-review/blob/main/scripts/PRISMA_pipeline_Fabio/mic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.10/dist-packages (0.28.1)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.10/dist-packages (from openai) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from openai) (4.66.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from openai) (3.8.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.20->openai) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->openai) (1.3.1)

In [ ]:
#Note: The openai-python library support for Azure OpenAI is in preview.
import os
import openai
import pandas as pd
from google.colab import drive as gdrive
import json
openai.api_type = "azure"
openai.api_base = "https://literature-review-autism.openai.azure.com/"
openai.api_version = "2023-07-01-preview"
openai.api_key = os.getenv("AZURE_OPENAI_API_KEY")

In [ ]:
gdrive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Define the folder containing the subfolders with CSV files
main_folder = '/content/drive/MyDrive/[ICON fellowship] social robot and autism/AI for behavioral analysis and autism/queries'

In [ ]:
df_input_file = f'{main_folder}/autism_ai_behavior_diagnosis_formatted__controlled_combined_noduplicates_semanticallyfiltered.csv'

In [ ]:
df = pd.read_csv(df_input_file)
df

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year,Database,text
0,"""Mommy Blogs"" and the Vaccination Exemption Na...",Social media offer an unprecedented opportunit...,"['Internet', 'attitudes', 'health knowledge', ...",10.2196/publichealth.6586,https://pubmed.ncbi.nlm.nih.gov/27876690/,"Tangherlini, Roychowdhury, Glenn, Crespi, Band...",JMIR public health and surveillance,2016.0,PubMed,"Title: ""Mommy Blogs"" and the Vaccination Exemp..."
1,"""Sequencing Matters"": Investigating Suitable A...",Social robots have been shown to be promising ...,"['action selection', 'attention skills', 'auti...",10.3389/frobt.2022.784249,https://pubmed.ncbi.nlm.nih.gov/35356059/,"Baraka, Couto, Melo, Paiva, Veloso",Frontiers in robotics and AI,2022.0,PubMed,"Title: ""Sequencing Matters"": Investigating Sui..."
2,"""Um"" and ""Uh"" Usage Patterns in Children with ...","Pragmatic language difficulties, including unu...","['Autism', 'Disfluency', 'Fillers', 'Natural l...",10.1007/s10803-022-05565-4,https://pubmed.ncbi.nlm.nih.gov/35499654/,"Lawley, Bedrick, MacFarlane, Dolata, Salem, Fo...",Journal of autism and developmental disorders,2023.0,PubMed,"Title: ""Um"" and ""Uh"" Usage Patterns in Childre..."
3,'SenseA'-Autism Early Signs and Pre-Aggressive...,This paper presents an efficient solution for ...,autism early signs; computer vision; feature e...,10.1109/AMS.2017.28,https://www.scopus.com/inward/record.uri?eid=2...,Gamaethige C.; Gunathilake U.; Jayasena D.; Ma...,AMS 2017 - Asia Modelling Symposium 2017 and 1...,2018.0,Scopus,Title: 'SenseA'-Autism Early Signs and Pre-Agg...
4,25th Annual Computational Neuroscience Meeting...,A1 Functional advantages of cell-type heteroge...,NaN,10.1186/s12868-016-0283-6,https://pubmed.ncbi.nlm.nih.gov/27534393/,NaN,BMC neuroscience,2016.0,PubMed,Title: 25th Annual Computational Neuroscience ...
...,...,...,...,...,...,...,...,...,...,...
1832,rs-fMRI Analysis Using Spatio-Temporal Sparse ...,Neuropsychiatric diseases such as Autism Spect...,CNN; Deep Learning; fMRI; Image Processing; Su...,10.1109/SIU55565.2022.9864751,https://www.scopus.com/inward/record.uri?eid=2...,Yener F.M.; Yildiz S.; Hafeez M.A.; Kayasandik...,2022 30th Signal Processing and Communications...,2022.0,Scopus,Title: rs-fMRI Analysis Using Spatio-Temporal ...
1833,rs-fMRI and machine learning for ASD diagnosis...,Autism Spectrum Disorder (ASD) diagnosis is st...,NaN,10.1038/s41598-022-09821-6,https://pubmed.ncbi.nlm.nih.gov/35411059/,"Santana, de Carvalho, Rodrigues, Bastos, de So...",Scientific reports,2022.0,PubMed,Title: rs-fMRI and machine learning for ASD di...
1834,sha-Early Intervention for children at risk of...,Autism Spectrum Disorder (ASD) is a developmen...,Autism Spectrum Disorder; CNN; Cognitive devel...,10.1109/I4Tech55392.2022.9952803,https://www.scopus.com/inward/record.uri?eid=2...,Shetty T.; Zope V.; Dandekar M.; Devnani A.; M...,2022 International Conference on Industry 4.0 ...,2022.0,Scopus,Title: sha-Early Intervention for children at ...
1835,‘Autistic Robots’ for Embodied Emulation of Be...,The goal of this work is to enable interaction...,NaN,10.1007/978-3-319-70022-9_11,https://www.scopus.com/inward/record.uri?eid=2...,Baraka K.; Melo F.S.; Veloso M.,Lecture Notes in Computer Science (including s...,2017.0,Scopus,Title: ‘Autistic Robots’ for Embodied Emulatio...
1836,“iCub Says: Do My Motor Sounds Disturb You?” M...,"In Socially Assistive Robotics, robots are use...",Auditory sensitivity; Autism spectrum disorder...,10.1007/978-3-030-90525-5_56,https://www.scopus.com/inward/record.uri?eid=2...,Chevalier P.; Floris F.; Priolo T.; De Tommaso...,Lecture Notes in Computer Science (including s...,2021.0,Scopus,Title: “iCub Says: Do My Motor Sounds Disturb ...

In [ ]:
'''
	{
		"role": "user",
		"content": "Title: A Review of Machine Learning Methods of Feature Selection and Classification for Autism Spectrum Disorder.    \nAbstract: Autism Spectrum Disorder (ASD), according to DSM-5 in the American Psychiatric Association, is a neurodevelopmental disorder that includes deficits of social communication and social interaction with the presence of restricted and repetitive behaviors. Children with ASD have difficulties in joint attention and social reciprocity, using non-verbal and verbal behavior for communication. Due to these deficits, children with autism are often socially isolated. Researchers have emphasized the importance of early identification and early intervention to improve the level of functioning in language, communication, and well-being of children with autism. However, due to limited local assessment tools to diagnose these children, limited speech-language therapy services in rural areas, etc., these children do not get the rehabilitation they need until they get into compulsory schooling at the age of seven years old. Hence, efficient approaches towards early identification and intervention through...)    \Keywords: FEATURE selection, AUTISM spectrum disorders, MACHINE learning, ARTIFICIAL neural networks, AUTISTIC children, SPEECH therapy education, autism spectrum disorder, classification, feature selection, imbalanced data, machine learning, AMERICAN Psychiatric Association"
	},
	{
		"role": "assistant",
		"content": "{1: true, 2: false, 3: false, 4: false, 5: true, 6: true, 7: false, \"rational\":\nThe paper is in English (1) and is not an empirical study (it's a literature review) (2). The study does not involve humans (3). The paper does not include participants diagnosed with ASD or suspected to have ASD (4) but directly addresses the assessment/screening/diagnosis of autism (5). The study involves the application of artificial intelligence (AI) (6) but does not make use of behavioral data (7).}"
	},

'''
'''
examples = [
	{
		"role": "system",
		"content": "You are a tool for systematic literature review and are provided with some specific exclusion criteria:\n1- The paper is not in English.\n2- The paper is not about empirical experimentation.\n3- The study doesn't involve human participants.\n4- The study does not include participants (at least) suspected to have autism.\n5- The paper does not address assessment, screening, diagnosis, prediction, or detection of autism.\n6- The study does not involve the application of artificial intelligence (AI).\n7- The study makes use of behavioral data (e.g., gaze, movements, posture, facial expressions, voice and speech, play, social interaction, and emotions).\n\nComplete the following JSON template for each paper you analyze:\n{\"1\": <TRUE/FALSE/IDK>, \"2\": <TRUE/FALSE/IDK>, \"3\": <TRUE/FALSE/IDK>, \"4\": <TRUE/FALSE/IDK>, \"5\": <TRUE/FALSE/IDK>, \"6\": <TRUE/FALSE/IDK>, \"7\": <TRUE/FALSE/IDK>, \"rational\": \"<TEXT WITH MOTIVATIONS FOR YOUR RESPONSES, IN NUMERICAL ORDER>\"}\nIt's okay to say IDK if you don't know if the exclusion criteria are matched based on the info provided about the paper. It's better to say IDK than guessing true or false. When you say false, means that the paper will be excluded based on that criterium, true otherwise. Papers about treatment and not diagnosis/screening must be excluded, meaning 5 is false."
	},
	{
		"role": "user",
		"content": "Title: Influence of Excitation/Inhibition Imbalance on Local Processing Bias in Autism Spectrum Disorder  \nAbstract: People with autism spectrum disorder (ASD) tend to detect local patterns of visual stimuli more quickly than global patterns, which is opposite to the behavior of typically developing people. We hypothesized that the imbalance between excitation and inhibition neurons in the visual cortex causes the local processing bias observed in ASD. Stronger inhibitory connections could diminish the neural activities and thus prevent global feature integration, whereas properly balanced connections would enable the cortex to detect features of any size. We verified our hypothesis by employing a computational neural network called a neocognitron. Our experimental results demonstrated that the network with stronger inhibitory connections exhibited a local processing bias, whereas the network with properly adjusted connections showed a moderate global bias. Moreover, the networks with extremely strong or weak inhibitions revealed no perception bias. These results suggest that an excitation/inhibition imbalance causes multiple types of atypical perception in ASD. ¬© Cognitive Science Society, CogSci 2015.All rights reserved.  \Keywords: autism spectrum disorder; excitation/inhibition balance; local processing bias; neocognitron"
	},
	{
		"role": "assistant",
		"content": "{\"1\": true, \"2\": true, \"3\": false, \"4\": false, \"5\": true, \"6\": true, \"7\": true, \"rational\": \"The paper is in English (1) and is an empirical study (it is not a theoretical paper or a secondary source of information like meta-analyses or systematic literature reviews) (2). The study involves computational simulations without human data and not animal subjects (3). The paper includes participants diagnosed with ASD (4) and directly addresses the assessment/screening/diagnosis of autism (5). The study involves the application of artificial intelligence (AI) (6) and is about behavioral data (7).\"}"
	},
	{
		"role": "user",
		"content": "Title: Control learning rate for autism facial detection via deep transfer learning.      \nAbstract: Autism spectrum disorder (ASD) is a complex neurodevelopmental disorder that affects social interaction and communication. Early detection of ASD can significantly improve outcomes for individuals with the disorder, and there has been increasing interest in using machine learning techniques to aid in the diagnosis of ASD. One promising approach is the use of deep learning techniques, particularly convolutional neural networks (CNNs), to classify facial images as indicative of ASD or not. However, choosing a learning rate for optimizing the performance of these deep CNNs can be tedious and may not always result in optimal convergence. In this paper, we propose a novel approach called the control subgradient algorithm (CSA) for tackling ASD diagnosis based on facial images using deep CNNs. CSA is a variation of the subgradient method in which the learning rate is updated by a control step in each iteration of each epoch. We apply CSA to the popular DensNet-121 CNN model and evaluate its performance on a publicly available facial ASD dataset. Our results show that CSA is faster than the baseline method and improves the classification accuracy and loss compared to the baseline. We also demonstrate the effectiveness of using CSA with <math xmlns=\"http://www.w3.org/1998/Math/MathML\"><msub><mi>L</mi><mn>1</mn></msub></math>-regularization to further improve the performance of our deep CNN model.      \Keywords: ['Autism facial detection', 'Deep neural networks', 'Learning rate', 'Nonsmooth optimization', 'Subgradient algorithm']"
	},
	{
		"role": "assistant",
		"content": "{\"1\": true, \"2\": true, \"3\": false, \"4\": true, \"5\": false, \"6\": true, \"7\": true, \"rational\": \"The paper is in English (1) and is about machine learning techniques for the diagnosis of ASD (2). The study does not involve animal subjects or human subjects (3) but includes participants diagnosed with or suspected to have ASD (4). The paper does not directly address the assessment, screening, diagnosis, or detection of autism (5) but involves the application of artificial intelligence (AI) (6) and makes use of behavioral data in the form of facial images (7).\"}"
	},
	{
		"role": "user",
		"content": "Title: A Randomized Controlled Trial of an Intelligent Robotic Response to Joint Attention Intervention System.                        \nAbstract: Although there has been growing interest in utilizing robots for intervention in autism spectrum disorder (ASD), there have been very few controlled trials to assess the actual impacts of such systems on social communication vulnerabilities. This study reports a randomized controlled trial to investigate a robot-mediated response to joint attention intervention in a small (23 recruited; 20 completed) group of young children (average age‚Äâ=‚Äâ2.54¬†years) with ASD. Small and nonsignificant group differences were observed regarding improvements in response to joint attention skills within and beyond the intervention. The sample showed tremendous individual variability in response to the system. Results highlight the current challenges related to developing pragmatic, beneficial, and generalizable robotic intervention systems for the targeted population.                        \Keywords: ['Autism spectrum disorder', 'Controlled trials', 'Response to joint attention', 'Robotics', 'Technology']"
	},
	{
		"role": "assistant",
		"content": "{\"1\": true, \"2\": true, \"3\": true, \"4\": true, \"5\": true, \"6\": true, \"7\": true, \"rational\": \"The paper is in English (1) and involves empirical experimentation (2). The study involves human participants (3) and they are all diagnosed with ASD (4). The paper directly addresses autism treatment and not assessment (5) and involves the application of artificial intelligence (AI) (6) and the use of behavioral data in the form of social communication skills (7).\"}"
	},
	{
		"role": "user",
		"content": "Title: Using 2D video-based pose estimation for automated prediction of autism spectrum disorders in young children.      \nAbstract: Clinical research in autism has recently witnessed promising digital phenotyping results, mainly focused on single feature extraction, such as gaze, head turn on name-calling or visual tracking of the moving object. The main drawback of these studies is the focus on relatively isolated behaviors elicited by largely controlled prompts. We recognize that while the diagnosis process understands the indexing of the specific behaviors, ASD also comes with broad impairments that often transcend single behavioral acts. For instance, the atypical nonverbal behaviors manifest through global patterns of atypical postures and movements, fewer gestures used and often decoupled from visual contact, facial affect, speech. Here, we tested the hypothesis that a deep neural network trained on the non-verbal aspects of social interaction can effectively differentiate between children with ASD and their typically developing peers. Our model achieves an accuracy of 80.9% (F1 score: 0.818; precision: 0.784; recall: 0.854) with the prediction probability positively correlated to the overall level of symptoms of autism in social affect and repetitive and restricted behaviors domain. Provided the non-invasive and affordable nature of computer vision, our approach carries reasonable promises that a reliable machine-learning-based ASD screening may become a reality not too far in the future.      \Keywords: []"
	},
	{
		"role": "assistant",
		"content": "{\"1\": true, \"2\": true, \"3\": true, \"4\": true, \"5\": true, \"6\": true, \"7\": true, \"rational\": \"The paper is in English (1) and is about machine learning methods for the prediction of ASD (2). The study involves human participants (3) and includes participants suspected to have ASD (4) and directly addresses the assessment, screening, diagnosis, prediction, or detection of autism (5). The study involves the application of artificial intelligence (AI) (6) and makes use of behavioral data in the form of non-verbal aspects of social interaction (7).\"}"
	},
	{
		"role": "user",
		"content": "Title: Machine Learning for Differential Diagnosis Between Clinical Conditions With Social Difficulty: Autism Spectrum Disorder, Early Psychosis, and Social Anxiety Disorder.  \nAbstract: Differential diagnosis in adult cohorts with social difficulty is confounded by comorbid mental health conditions, common etiologies, and shared phenotypes. Identifying shared and discriminating profiles can facilitate intervention and remediation strategies. The objective of the study was to identify salient features of a composite test battery of cognitive and mood measures using a machine learning paradigm in clinical cohorts with social interaction difficulties. We recruited clinical participants who met standardized diagnostic criteria for autism spectrum disorder (ASD: n = 62), early psychosis (EP: n = 48), or social anxiety disorder (SAD: N = 83) and compared them with a neurotypical comparison group (TYP: N = 43). Using five machine-learning algorithms and repeated cross-validation, we trained and tested classification models using measures of cognitive and executive function, lower- and higher-order social cognition and mood severity. Performance metrics were the area under the curve (AUC) and Brier Scores. Sixteen features successfully differentiated between the groups. The control versus social impairment cohorts (ASD, EP, SAD) were differentiated by social cognition, visuospatial memory and mood measures. Importantly, a distinct profile cluster drawn from social cognition, visual learning, executive function and mood, distinguished the neurodevelopmental cohort (EP and ASD) from the SAD group. The mean AUC range was between 0.891 and 0.916 for social impairment versus control cohorts and, 0.729 to 0.781 for SAD vs neurodevelopmental cohorts. This is the first study that compares an extensive battery of neuropsychological and self-report measures using a machine learning protocol in clinical and neurodevelopmental cohorts characterized by social impairment. Findings are relevant for diagnostic, intervention and remediation strategies for these groups.  \Keywords: ['autism spectrum disorder', 'cognition', 'differential diagnosis', 'early psychosis', 'machine learning', 'social anxiety disorder']"
	},
	{
		"role": "assistant",
		"content": "{\"1\": true, \"2\": true, \"3\": true, \"4\": true, \"5\": true, \"6\": true, \"7\": false, \"rational\": \"The paper is in English (1) and is about an empirical study (2). The study does not involve animal subjects or computational simulations and includes human participants (3). The paper includes participants diagnosed with ASD (4) and directly addresses the assessment, screening, diagnosis, or detection of autism, early psychosis, and social anxiety disorder (5). The study involves the application of artificial intelligence (AI) (6) but does not make use of behavioral data - they use an extensive battery of neuropsychological and self-report measures (7).\"}"
	},
	{
		"role": "user",
		"content": "Title: A machine learning-based diagnostic model for children with autism spectrum disorders complicated with intellectual disability.  \nAbstract: Early detection of children with autism spectrum disorder (ASD) and comorbid intellectual disability (ID) can help in individualized intervention. Appropriate assessment and diagnostic tools are lacking in primary care. This study aims to explore the applicability of machine learning (ML) methods in diagnosing ASD comorbid ID compared with traditional regression models.From January 2017 to December 2021, 241 children with ASD, with an average age of 6.41 ¬± 1.96, diagnosed in the Developmental Behavior Department of the Children's Hospital Affiliated with the Medical College of Zhejiang University were included in the analysis. This study trained the traditional diagnostic models of Logistic regression (LR), Support Vector Machine (SVM), and two ensemble learning algorithms [Random Forest (RF) and XGBoost]. Socio-demographic and behavioral observation data were used to distinguish whether autistic children had combined ID. The hyperparameters adjustment uses grid search and 10-fold validation. The Boruta method is used to select variables. The model's performance was evaluated using discrimination, calibration, and decision curve analysis (DCA).Among 241 autistic children, 98 (40.66%) were ASD comorbid ID. The four diagnostic models can better distinguish whether autistic children are complicated with ID, and the accuracy of SVM is the highest (0.836); SVM and XGBoost have better accuracy (0.800, 0.838); LR has the best sensitivity (0.939), followed by SVM (0.952). Regarding specificity, SVM, RF, and XGBoost performed significantly higher than LR (0.355). The AUC of ML (SVM, 0.835 [95% CI: 0.747-0.944]; RF, 0.829 [95% CI: 0.738-0.920]; XGBoost, 0.845 [95% CI: 0.734-0.937]) is not different from traditional LR (0.858 [95% CI: 0.770-0.944]). Only SVM observed a good calibration degree. Regarding DCA, LR, and SVM have higher benefits in a wider threshold range.Compared to the traditional regression model, ML model based on socio-demographic and behavioral observation data, especially SVM, has a better ability to distinguish whether autistic children are combined with ID.  \Keywords: ['artificial intelligence', 'autism spectrum disorder', 'child', 'diagnostic model', 'intellectual disability', 'machine learning']"
	},
	{
		"role": "assistant",
		"content": "{\"1\": true, \"2\": true, \"3\": true, \"4\": true, \"5\": true, \"6\": true, \"7\": true, \"rational\": \"The paper is in English (1) and is an empirical study (2). The study involves human participants (3) and includes participants diagnosed with ASD and comorbid ID (4). The paper directly addresses the assessment, screening, diagnosis, prediction, or detection of autism and comorbid ID (5) and involves the application of artificial intelligence (AI) through the use of machine learning methods (6) and the use of behavioral data in the form of socio-demographic and behavioral observation data (7).\"}"
	},
	{
		"role": "user",
		"content": "Title: Diagnostic classification of autism using resting-state fMRI data improves with full correlation functional brain connectivity compared to partial correlation.  \nAbstract: Autism Spectrum Disorder (ASD) is a neurodevelopmental disability with altered connectivity in brain networks.In this study, brain connections in Resting-state functional Magnetic Resonance Imaging (Rs-fMRI) of ASD and Typical Developing (TD) are analyzed by partial and full correlation methods such as Gaussian Graphical Least Absolute Shrinkage and Selection Operator (GLASSO), Max-Det Matrix Completion (MDMC), and Pearson Correlation Co-Efficient (PCCE). We investigated Functional Connectivity (FC) of ASD and TD brain from 238 functionally defined regions of interest. Furthermore, we constructed a series of feature sets by applying conditional random forests and conditional permutation importance. We built classifier models by Random Forest (RF), Oblique RF (ORF), Support Vector Machine (SVM), and Convolutional Neural Network (CNN) for each feature set. FC features are ranked based on p-value and we analyzed the top 20 FC features.We achieved a single-trial test accuracy of 72.5 %, though MDMC-SVM and PCCE-CNN pipelines. Further, PCCE-CNN pipeline gives better average test accuracy (70.31 %) and area under the curve (0.73) compared to other pipelines. We found that top-20 PCCE based FC features are from networks such as Dorsal Attention (DA), Cingulo-Opercular Task Control (COTC), somatosensory motor hand and subcortical. In addition, among top 20 PCCE features, many FC links are found between COTC and DA (4 connections) which helped to discriminate the ASD and TD.The generalized classifier models built in our study for highly heterogeneous participants perform better than previous studies with similar data sets and diagnostic groups.  \Keywords: ['Autism spectrum disorder', 'Brain networks', 'Functional connectivity', 'Partial and full correlation', 'Rs-fMRI']"
	},
	{
		"role": "assistant",
		"content": "{\"1\": true, \"2\": true, \"3\": true, \"4\": true, \"5\": true, \"6\": true, \"7\": false, \"rational\": \"The paper is in English (1) and is an empirical study (2). The study involves human participants (3) and includes participants diagnosed with ASD (4) and directly addresses the assessment, screening, diagnosis, or detection of autism (5). The study involves the application of artificial intelligence (AI) (6) but does not make use of behavioral data - they use resting-state functional Magnetic Resonance Imaging (Rs-fMRI) data to analyze brain connectivity (7).\""
	},
	{
		"role": "user",
		"content": "Title: Children ASD Evaluation Through Joint Analysis of EEG and Eye-Tracking Recordings With Graph Convolution Network.  \nAbstract: Recent advances in neuroscience indicate that analysis of bio-signals such as rest state electroencephalogram (EEG) and eye-tracking data can provide more reliable evaluation of children autism spectrum disorder (ASD) than traditional methods of behavior measurement relying on scales do. However, the effectiveness of the new approaches still lags behind the increasing requirement in clinical or educational practices as the \"bio-marker\" information carried by the bio-signal of a single-modality is likely insufficient or distorted. This study proposes an approach to joint analysis of EEG and eye-tracking for children ASD evaluation. The approach focuses on deep fusion of the features in two modalities as no explicit correlations between the original bio-signals are available, which also limits the performance of existing methods along this direction. First, the synchronization measures, information entropy, and time-frequency features of the multi-channel EEG are derived. Then a random forest applies to the eye-tracking recordings of the same subjects to single out the most significant features. A graph convolutional network (GCN) model then naturally fuses the two group of features to differentiate the children with ASD from the typically developed (TD) subjects. Experiments have been carried out on the two types of the bio-signals collected from 42 children (21 ASD and 21 TD subjects, 3-6 years old). The results indicate that (1) the proposed approach can achieve an accuracy of 95% in ASD detection, and (2) strong correlations exist between the two bio-signals collected even asynchronously, in particular the EEG synchronization against the face related/joint attentions in terms of covariance.  \Keywords: ['EEG', 'autism spectrum disorder', 'eye-tracking', 'graph convolution network', 'multi-modality fusion']"
	},
	{
		"role": "assistant",
		"content": "{\"1\": true, \"2\": true, \"3\": true, \"4\": true, \"5\": true, \"6\": true, \"7\": true, \"rational\": \"The paper is in English (1) and is an empirical study (2). The study involves human participants (3) and includes participants diagnosed with ASD (4) and directly addresses the assessment, screening, diagnosis, or detection of autism (5). The study involves the application of artificial intelligence (AI) (6) and makes use of behavioral data in the form of eye-tracking recordings (EEG is not considered behavioral data) (7).\"}"
	}
]
'''

'\nexamples = [\n\t{\n\t\t"role": "system",\n\t\t"content": "You are a tool for systematic literature review and are provided with some specific exclusion criteria:\n1- The paper is not in English.\n2- The paper is not about empirical experimentation.\n3- The study doesn\'t involve human participants.\n4- The study does not include participants (at least) suspected to have autism.\n5- The paper does not address assessment, screening, diagnosis, prediction, or detection of autism.\n6- The study does not involve the application of artificial intelligence (AI).\n7- The study makes use of behavioral data (e.g., gaze, movements, posture, facial expressions, voice and speech, play, social interaction, and emotions).\n\nComplete the following JSON template for each paper you analyze:\n{"1": <TRUE/FALSE/IDK>, "2": <TRUE/FALSE/IDK>, "3": <TRUE/FALSE/IDK>, "4": <TRUE/FALSE/IDK>, "5": <TRUE/FALSE/IDK>, "6": <TRUE/FALSE/IDK>, "7": <TRUE/FALSE/IDK>, "rational": "<TEXT WITH MOTIVATIONS FOR YOUR RESPONSES, IN NUMERICAL ORDER>"}\nIt\'s okay to say IDK if you don\'t know if the exclusion criteria are matched based on the info provided about the paper. It\'s better to say IDK than guessing true or false. When you say false, means that the paper will be excluded based on that criterium, true otherwise. Papers about treatment and not diagnosis/screening must be excluded, meaning 5 is false."\n\t},\n\t{\n\t\t"role": "user",\n\t\t"content": "Title: Influence of Excitation/Inhibition Imbalance on Local Processing Bias in Autism Spectrum Disorder  \nAbstract: People with autism spectrum disorder (ASD) tend to detect local patterns of visual stimuli more quickly than global patterns, which is opposite to the behavior of typically developing people. We hypothesized that the imbalance between excitation and inhibition neurons in the visual cortex causes the local processing bias observed in ASD. Stronger inhibitory connections could diminish the neural activities and thus prevent global feature integration, whereas properly balanced connections would enable the cortex to detect features of any size. We verified our hypothesis by employing a computational neural network called a neocognitron. Our experimental results demonstrated that the network with stronger inhibitory connections exhibited a local processing bias, whereas the network with properly adjusted connections showed a moderate global bias. Moreover, the networks with extremely strong or weak inhibitions revealed no perception bias. These results suggest that an excitation/inhibition imbalance causes multiple types of atypical perception in ASD. ¬© Cognitive Science Society, CogSci 2015.All rights reserved.  \\Keywords: autism spectrum disorder; excitation/inhibition balance; local processing bias; neocognitron"\n\t},\n\t{\n\t\t"role": "assistant",\n\t\t"content": "{"1": true, "2": true, "3": false, "4": false, "5": true, "6": true, "7": true, "rational": "The paper is in English (1) and is an empirical study (it is not a theoretical paper or a secondary source of information like meta-analyses or systematic literature reviews) (2). The study involves computational simulations without human data and not animal subjects (3). The paper includes participants diagnosed with ASD (4) and directly addresses the assessment/screening/diagnosis of autism (5). The study involves the application of artificial intelligence (AI) (6) and is about behavioral data (7)."}"\n\t},\n\t{\n\t\t"role": "user",\n\t\t"content": "Title: Control learning rate for autism facial detection via deep transfer learning.      \nAbstract: Autism spectrum disorder (ASD) is a complex neurodevelopmental disorder that affects social interaction and communication. Early detection of ASD can significantly improve outcomes for individuals with the disorder, and there has been increasing interest in using machine learning techniques to aid in the diagnosis of ASD. One promising approach is the use of deep learning techniques, particularly convolutional neural networks (CNNs), to classify facial images as indicative of ASD or not. However, choosing a learning rate for optimizing the performance of these deep CNNs can be tedious and may not always result in optimal convergence. In this paper, we propose a novel approach called the control subgradient algorithm (CSA) for tackling ASD diagnosis based on facial images using deep CNNs. CSA is a variation of the subgradient method in which the learning rate is updated by a control step in each iteration of each epoch. We apply CSA to the popular DensNet-121 CNN model and evaluate its performance on a publicly available facial ASD dataset. Our results show that CSA is faster than the baseline method and improves the classification accuracy and loss compared to the baseline. We also demonstrate the effectiveness of using CSA with <math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mi>L</mi><mn>1</mn></msub></math>-regularization to further improve the performance of our deep CNN model.      \\Keywords: [\'Autism facial detection\', \'Deep neural networks\', \'Learning rate\', \'Nonsmooth optimization\', \'Subgradient algorithm\']"\n\t},\n\t{\n\t\t"role": "assistant",\n\t\t"content": "{"1": true, "2": true, "3": false, "4": true, "5": false, "6": true, "7": true, "rational": "The paper is in English (1) and is about machine learning techniques for the diagnosis of ASD (2). The study does not involve animal subjects or human subjects (3) but includes participants diagnosed with or suspected to have ASD (4). The paper does not directly address the assessment, screening, diagnosis, or detection of autism (5) but involves the application of artificial intelligence (AI) (6) and makes use of behavioral data in the form of facial images (7)."}"\n\t},\n\t{\n\t\t"role": "user",\n\t\t"content": "Title: A Randomized Controlled Trial of an Intelligent Robotic Response to Joint Attention Intervention System.                        \nAbstract: Although there has been growing interest in utilizing robots for intervention in autism spectrum disorder (ASD), there have been very few controlled trials to assess the actual impacts of such systems on social communication vulnerabilities. This study reports a randomized controlled trial to investigate a robot-mediated response to joint attention intervention in a small (23 recruited; 20 completed) group of young children (average age‚Äâ=‚Äâ2.54¬†years) with ASD. Small and nonsignificant group differences were observed regarding improvements in response to joint attention skills within and beyond the intervention. The sample showed tremendous individual variability in response to the system. Results highlight the current challenges related to developing pragmatic, beneficial, and generalizable robotic intervention systems for the targeted population.                        \\Keywords: [\'Autism spectrum disorder\', \'Controlled trials\', \'Response to joint attention\', \'Robotics\', \'Technology\']"\n\t},\n\t{\n\t\t"role": "assistant",\n\t\t"content": "{"1": true, "2": true, "3": true, "4": true, "5": true, "6": true, "7": true, "rational": "The paper is in English (1) and involves empirical experimentation (2). The study involves human participants (3) and they are all diagnosed with ASD (4). The paper directly addresses autism treatment and not assessment (5) and involves the application of artificial intelligence (AI) (6) and the use of behavioral data in the form of social communication skills (7)."}"\n\t},\n\t{\n\t\t"role": "user",\n\t\t"content": "Title: Using 2D video-based pose estimation for automated prediction of autism spectrum disorders in young children.      \nAbstract: Clinical research in autism has recently witnessed promising digital phenotyping results, mainly focused on single feature extraction, such as gaze, head turn on name-calling or visual tracking of the moving object. The main drawback of these studies is the focus on relatively isolated behaviors elicited by largely controlled prompts. We recognize that while the diagnosis process understands the indexing of the specific behaviors, ASD also comes with broad impairments that often transcend single behavioral acts. For instance, the atypical nonverbal behaviors manifest through global patterns of atypical postures and movements, fewer gestures used and often decoupled from visual contact, facial affect, speech. Here, we tested the hypothesis that a deep neural network trained on the non-verbal aspects of social interaction can effectively differentiate between children with ASD and their typically developing peers. Our model achieves an accuracy of 80.9% (F1 score: 0.818; precision: 0.784; recall: 0.854) with the prediction probability positively correlated to the overall level of symptoms of autism in social affect and repetitive and restricted behaviors domain. Provided the non-invasive and affordable nature of computer vision, our approach carries reasonable promises that a reliable machine-learning-based ASD screening may become a reality not too far in the future.      \\Keywords: []"\n\t},\n\t{\n\t\t"role": "assistant",\n\t\t"content": "{"1": true, "2": true, "3": true, "4": true, "5": true, "6": true, "7": true, "rational": "The paper is in English (1) and is about machine learning methods for the prediction of ASD (2). The study involves human participants (3) and includes participants suspected to have ASD (4) and directly addresses the assessment, screening, diagnosis, prediction, or detection of autism (5). The study involves the application of artificial intelligence (AI) (6) and makes use of behavioral data in the form of non-verbal aspects of social interaction (7)."}"\n\t},\n\t{\n\t\t"role": "user",\n\t\t"content": "Title: Machine Learning for Differential Diagnosis Between Clinical Conditions With Social Difficulty: Autism Spectrum Disorder, Early Psychosis, and Social Anxiety Disorder.  \nAbstract: Differential diagnosis in adult cohorts with social difficulty is confounded by comorbid mental health conditions, common etiologies, and shared phenotypes. Identifying shared and discriminating profiles can facilitate intervention and remediation strategies. The objective of the study was to identify salient features of a composite test battery of cognitive and mood measures using a machine learning paradigm in clinical cohorts with social interaction difficulties. We recruited clinical participants who met standardized diagnostic criteria for autism spectrum disorder (ASD: n = 62), early psychosis (EP: n = 48), or social anxiety disorder (SAD: N = 83) and compared them with a neurotypical comparison group (TYP: N = 43). Using five machine-learning algorithms and repeated cross-validation, we trained and tested classification models using measures of cognitive and executive function, lower- and higher-order social cognition and mood severity. Performance metrics were the area under the curve (AUC) and Brier Scores. Sixteen features successfully differentiated between the groups. The control versus social impairment cohorts (ASD, EP, SAD) were differentiated by social cognition, visuospatial memory and mood measures. Importantly, a distinct profile cluster drawn from social cognition, visual learning, executive function and mood, distinguished the neurodevelopmental cohort (EP and ASD) from the SAD group. The mean AUC range was between 0.891 and 0.916 for social impairment versus control cohorts and, 0.729 to 0.781 for SAD vs neurodevelopmental cohorts. This is the first study that compares an extensive battery of neuropsychological and self-report measures using a machine learning protocol in clinical and neurodevelopmental cohorts characterized by social impairment. Findings are relevant for diagnostic, intervention and remediation strategies for these groups.  \\Keywords: [\'autism spectrum disorder\', \'cognition\', \'differential diagnosis\', \'early psychosis\', \'machine learning\', \'social anxiety disorder\']"\n\t},\n\t{\n\t\t"role": "assistant",\n\t\t"content": "{"1": true, "2": true, "3": true, "4": true, "5": true, "6": true, "7": false, "rational": "The paper is in English (1) and is about an empirical study (2). The study does not involve animal subjects or computational simulations and includes human participants (3). The paper includes participants diagnosed with ASD (4) and directly addresses the assessment, screening, diagnosis, or detection of autism, early psychosis, and social anxiety disorder (5). The study involves the application of artificial intelligence (AI) (6) but does not make use of behavioral data - they use an extensive battery of neuropsychological and self-report measures (7)."}"\n\t},\n\t{\n\t\t"role": "user",\n\t\t"content": "Title: A machine learning-based diagnostic model for children with autism spectrum disorders complicated with intellectual disability.  \nAbstract: Early detection of children with autism spectrum disorder (ASD) and comorbid intellectual disability (ID) can help in individualized intervention. Appropriate assessment and diagnostic tools are lacking in primary care. This study aims to explore the applicability of machine learning (ML) methods in diagnosing ASD comorbid ID compared with traditional regression models.From January 2017 to December 2021, 241 children with ASD, with an average age of 6.41 ¬± 1.96, diagnosed in the Developmental Behavior Department of the Children\'s Hospital Affiliated with the Medical College of Zhejiang University were included in the analysis. This study trained the traditional diagnostic models of Logistic regression (LR), Support Vector Machine (SVM), and two ensemble learning algorithms [Random Forest (RF) and XGBoost]. Socio-demographic and behavioral observation data were used to distinguish whether autistic children had combined ID. The hyperparameters adjustment uses grid search and 10-fold validation. The Boruta method is used to select variables. The model\'s performance was evaluated using discrimination, calibration, and decision curve analysis (DCA).Among 241 autistic children, 98 (40.66%) were ASD comorbid ID. The four diagnostic models can better distinguish whether autistic children are complicated with ID, and the accuracy of SVM is the highest (0.836); SVM and XGBoost have better accuracy (0.800, 0.838); LR has the best sensitivity (0.939), followed by SVM (0.952). Regarding specificity, SVM, RF, and XGBoost performed significantly higher than LR (0.355). The AUC of ML (SVM, 0.835 [95% CI: 0.747-0.944]; RF, 0.829 [95% CI: 0.738-0.920]; XGBoost, 0.845 [95% CI: 0.734-0.937]) is not different from traditional LR (0.858 [95% CI: 0.770-0.944]). Only SVM observed a good calibration degree. Regarding DCA, LR, and SVM have higher benefits in a wider threshold range.Compared to the traditional regression model, ML model based on socio-demographic and behavioral observation data, especially SVM, has a better ability to distinguish whether autistic children are combined with ID.  \\Keywords: [\'artificial intelligence\', \'autism spectrum disorder\', \'child\', \'diagnostic model\', \'intellectual disability\', \'machine learning\']"\n\t},\n\t{\n\t\t"role": "assistant",\n\t\t"content": "{"1": true, "2": true, "3": true, "4": true, "5": true, "6": true, "7": true, "rational": "The paper is in English (1) and is an empirical study (2). The study involves human participants (3) and includes participants diagnosed with ASD and comorbid ID (4). The paper directly addresses the assessment, screening, diagnosis, prediction, or detection of autism and comorbid ID (5) and involves the application of artificial intelligence (AI) through the use of machine learning methods (6) and the use of behavioral data in the form of socio-demographic and behavioral observation data (7)."}"\n\t},\n\t{\n\t\t"role": "user",\n\t\t"content": "Title: Diagnostic classification of autism using resting-state fMRI data improves with full correlation functional brain connectivity compared to partial correlation.  \nAbstract: Autism Spectrum Disorder (ASD) is a neurodevelopmental disability with altered connectivity in brain networks.In this study, brain connections in Resting-state functional Magnetic Resonance Imaging (Rs-fMRI) of ASD and Typical Developing (TD) are analyzed by partial and full correlation methods such as Gaussian Graphical Least Absolute Shrinkage and Selection Operator (GLASSO), Max-Det Matrix Completion (MDMC), and Pearson Correlation Co-Efficient (PCCE). We investigated Functional Connectivity (FC) of ASD and TD brain from 238 functionally defined regions of interest. Furthermore, we constructed a series of feature sets by applying conditional random forests and conditional permutation importance. We built classifier models by Random Forest (RF), Oblique RF (ORF), Support Vector Machine (SVM), and Convolutional Neural Network (CNN) for each feature set. FC features are ranked based on p-value and we analyzed the top 20 FC features.We achieved a single-trial test accuracy of 72.5 %, though MDMC-SVM and PCCE-CNN pipelines. Further, PCCE-CNN pipeline gives better average test accuracy (70.31 %) and area under the curve (0.73) compared to other pipelines. We found that top-20 PCCE based FC features are from networks such as Dorsal Attention (DA), Cingulo-Opercular Task Control (COTC), somatosensory motor hand and subcortical. In addition, among top 20 PCCE features, many FC links are found between COTC and DA (4 connections) which helped to discriminate the ASD and TD.The generalized classifier models built in our study for highly heterogeneous participants perform better than previous studies with similar data sets and diagnostic groups.  \\Keywords: [\'Autism spectrum disorder\', \'Brain networks\', \'Functional connectivity\', \'Partial and full correlation\', \'Rs-fMRI\']"\n\t},\n\t{\n\t\t"role": "assistant",\n\t\t"content": "{"1": true, "2": true, "3": true, "4": true, "5": true, "6": true, "7": false, "rational": "The paper is in English (1) and is an empirical study (2). The study involves human participants (3) and includes participants diagnosed with ASD (4) and directly addresses the assessment, screening, diagnosis, or detection of autism (5). The study involves the application of artificial intelligence (AI) (6) but does not make use of behavioral data - they use resting-state functional Magnetic Resonance Imaging (Rs-fMRI) data to analyze brain connectivity (7).""\n\t},\n\t{\n\t\t"role": "user",\n\t\t"content": "Title: Children ASD Evaluation Through Joint Analysis of EEG and Eye-Tracking Recordings With Graph Convolution Network.  \nAbstract: Recent advances in neuroscience indicate that analysis of bio-signals such as rest state electroencephalogram (EEG) and eye-tracking data can provide more reliable evaluation of children autism spectrum disorder (ASD) than traditional methods of behavior measurement relying on scales do. However, the effectiveness of the new approaches still lags behind the increasing requirement in clinical or educational practices as the "bio-marker" information carried by the bio-signal of a single-modality is likely insufficient or distorted. This study proposes an approach to joint analysis of EEG and eye-tracking for children ASD evaluation. The approach focuses on deep fusion of the features in two modalities as no explicit correlations between the original bio-signals are available, which also limits the performance of existing methods along this direction. First, the synchronization measures, information entropy, and time-frequency features of the multi-channel EEG are derived. Then a random forest applies to the eye-tracking recordings of the same subjects to single out the most significant features. A graph convolutional network (GCN) model then naturally fuses the two group of features to differentiate the children with ASD from the typically developed (TD) subjects. Experiments have been carried out on the two types of the bio-signals

In [ ]:
'''
examples = [
	{
		"role": "system",
		"content":
      """
      You are a tool for systematic scientific literature review and are provided with a list of specific criteria to verify:
      1- The paper is in English.
      2- The paper explicitly mentions the design, execution, or results of an empirical investigation, and does not primarily focus on opinion, argumentation, or solely summarizing existing literature.
      3- The paper is a literature review.
      4- The paper does involve at least one participant.
      5- The study involves animals as participants.
      6- In the study there are some participants who have autism or are suspected to have autism.
      7- The paper does address assessment, screening, diagnosis, prediction, or detection of autism, and not only training/therapy/treatment.
      8- The study does involve the application of artificial intelligence (AI).
      9- The study makes use of behavioral data (e.g., gaze, movements, posture, facial expressions, voice and speech, play, social interaction, and emotions).

      Complete the following JSON template for each paper you analyze:\n{\"1\": <TRUE/FALSE/NOT DEFINED>, \"2\": <TRUE/FALSE/NOT DEFINED>, \"3\": <TRUE/FALSE/NOT DEFINED>, \"4\": <TRUE/FALSE/NOT DEFINED>, \"5\": <TRUE/FALSE/NOT DEFINED>, \"6\": <TRUE/FALSE/NOT DEFINED>, \"7\": <TRUE/FALSE/NOT DEFINED>, \"8\": <TRUE/FALSE/NOT DEFINED>, \"9\": <TRUE/FALSE/NOT DEFINED>, \"rational\": \"<TEXT WITH MOTIVATIONS FOR YOUR RESPONSES. ONE SENTECE FOR EACH BULLET POINT.\"}
      If the info is not provided, please say \"NOT DEFINED\".
      """
	}
]
'''

'\nexamples = [\n\t{\n\t\t"role": "system",\n\t\t"content": \n      """\n      You are a tool for systematic scientific literature review and are provided with a list of specific criteria to verify: \n      1- The paper is in English.\n      2- The paper explicitly mentions the design, execution, or results of an empirical investigation, and does not primarily focus on opinion, argumentation, or solely summarizing existing literature.\n      3- The paper is a literature review.\n      4- The paper does involve at least one participant.\n      5- The study involves animals as participants.\n      6- In the study there are some participants who have autism or are suspected to have autism.\n      7- The paper does address assessment, screening, diagnosis, prediction, or detection of autism, and not only training/therapy/treatment.\n      8- The study does involve the application of artificial intelligence (AI).\n      9- The study makes use of behavioral data (e.g., gaze, movements, posture, facial expressions, voice and speech, play, social interaction, and emotions).\n      \n      Complete the following JSON template for each paper you analyze:\n{"1": <TRUE/FALSE/NOT DEFINED>, "2": <TRUE/FALSE/NOT DEFINED>, "3": <TRUE/FALSE/NOT DEFINED>, "4": <TRUE/FALSE/NOT DEFINED>, "5": <TRUE/FALSE/NOT DEFINED>, "6": <TRUE/FALSE/NOT DEFINED>, "7": <TRUE/FALSE/NOT DEFINED>, "8": <TRUE/FALSE/NOT DEFINED>, "9": <TRUE/FALSE/NOT DEFINED>, "rational": "<TEXT WITH MOTIVATIONS FOR YOUR RESPONSES. ONE SENTECE FOR EACH BULLET POINT."}\n      If the info is not provided, please say "NOT DEFINED".\n      """\n\t}\n]\n'

In [ ]:
examples = [
    {
        "role": "system",
        "content":
        """
        Answer true or false for each question:
        1- Are the paper's title and abstract written in English?
        2- Based on the paper's title, abstract and keywords, is the paper a literature review?
        3- Based on the paper's title, abstract and keywords, does the study involve at least one participant?
        4- Based on the paper's title, abstract and keywords, are there only animals participants in the study?
        5- Based on the paper's title, abstract and keywords, do some participants have autism?
        6- Based on the paper's title, abstract and keywords, does the paper address assessment, screening, diagnosis, prediction, or detection of autism, not just training/therapy/treatment?
        7- Based on the paper's title, abstract and keywords, does the study involve artificial intelligence (AI), like machine-/deep-learning or robots?
        8- Based on the paper's title, abstract and keywords, does the study use behavioral data like gaze, movements, etc?
        9- Based on the paper's title, abstract and keywords, is at least one child a participant in the study?
        10- Does the abstract describe a single research study?

        Provide your answers in this JSON format:
        {"1": true/false, ..., "rational": "Brief and concise reason for 1, Brief and concise reason for 2, ..."}
        Do not use any other format.
        """
    }
]

In [ ]:
examples = [
    {
        "role": "system",
        "content":
        """
        Answer true or false:
        1- Does the abstract describe a single research study?

        Provide your answers in this JSON format:
        {"1": true/false, "rational": "Brief and concise reason for 1, Brief and concise reason for 2, ..."}
        Do not use any other format.
        """
    }
]

In [ ]:
pd.options.mode.chained_assignment = None  # Disable SettingWithCopyWarning

In [ ]:
df

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year,Database,text
0,"""Mommy Blogs"" and the Vaccination Exemption Na...",Social media offer an unprecedented opportunit...,"['Internet', 'attitudes', 'health knowledge', ...",10.2196/publichealth.6586,https://pubmed.ncbi.nlm.nih.gov/27876690/,"Tangherlini, Roychowdhury, Glenn, Crespi, Band...",JMIR public health and surveillance,2016.0,PubMed,"Title: ""Mommy Blogs"" and the Vaccination Exemp..."
1,"""Sequencing Matters"": Investigating Suitable A...",Social robots have been shown to be promising ...,"['action selection', 'attention skills', 'auti...",10.3389/frobt.2022.784249,https://pubmed.ncbi.nlm.nih.gov/35356059/,"Baraka, Couto, Melo, Paiva, Veloso",Frontiers in robotics and AI,2022.0,PubMed,"Title: ""Sequencing Matters"": Investigating Sui..."
2,"""Um"" and ""Uh"" Usage Patterns in Children with ...","Pragmatic language difficulties, including unu...","['Autism', 'Disfluency', 'Fillers', 'Natural l...",10.1007/s10803-022-05565-4,https://pubmed.ncbi.nlm.nih.gov/35499654/,"Lawley, Bedrick, MacFarlane, Dolata, Salem, Fo...",Journal of autism and developmental disorders,2023.0,PubMed,"Title: ""Um"" and ""Uh"" Usage Patterns in Childre..."
3,'SenseA'-Autism Early Signs and Pre-Aggressive...,This paper presents an efficient solution for ...,autism early signs; computer vision; feature e...,10.1109/AMS.2017.28,https://www.scopus.com/inward/record.uri?eid=2...,Gamaethige C.; Gunathilake U.; Jayasena D.; Ma...,AMS 2017 - Asia Modelling Symposium 2017 and 1...,2018.0,Scopus,Title: 'SenseA'-Autism Early Signs and Pre-Agg...
4,25th Annual Computational Neuroscience Meeting...,A1 Functional advantages of cell-type heteroge...,NaN,10.1186/s12868-016-0283-6,https://pubmed.ncbi.nlm.nih.gov/27534393/,NaN,BMC neuroscience,2016.0,PubMed,Title: 25th Annual Computational Neuroscience ...
...,...,...,...,...,...,...,...,...,...,...
1832,rs-fMRI Analysis Using Spatio-Temporal Sparse ...,Neuropsychiatric diseases such as Autism Spect...,CNN; Deep Learning; fMRI; Image Processing; Su...,10.1109/SIU55565.2022.9864751,https://www.scopus.com/inward/record.uri?eid=2...,Yener F.M.; Yildiz S.; Hafeez M.A.; Kayasandik...,2022 30th Signal Processing and Communications...,2022.0,Scopus,Title: rs-fMRI Analysis Using Spatio-Temporal ...
1833,rs-fMRI and machine learning for ASD diagnosis...,Autism Spectrum Disorder (ASD) diagnosis is st...,NaN,10.1038/s41598-022-09821-6,https://pubmed.ncbi.nlm.nih.gov/35411059/,"Santana, de Carvalho, Rodrigues, Bastos, de So...",Scientific reports,2022.0,PubMed,Title: rs-fMRI and machine learning for ASD di...
1834,sha-Early Intervention for children at risk of...,Autism Spectrum Disorder (ASD) is a developmen...,Autism Spectrum Disorder; CNN; Cognitive devel...,10.1109/I4Tech55392.2022.9952803,https://www.scopus.com/inward/record.uri?eid=2...,Shetty T.; Zope V.; Dandekar M.; Devnani A.; M...,2022 International Conference on Industry 4.0 ...,2022.0,Scopus,Title: sha-Early Intervention for children at ...
1835,‘Autistic Robots’ for Embodied Emulation of Be...,The goal of this work is to enable interaction...,NaN,10.1007/978-3-319-70022-9_11,https://www.scopus.com/inward/record.uri?eid=2...,Baraka K.; Melo F.S.; Veloso M.,Lecture Notes in Computer Science (including s...,2017.0,Scopus,Title: ‘Autistic Robots’ for Embodied Emulatio...
1836,“iCub Says: Do My Motor Sounds Disturb You?” M...,"In Socially Assistive Robotics, robots are use...",Auditory sensitivity; Autism spectrum disorder...,10.1007/978-3-030-90525-5_56,https://www.scopus.com/inward/record.uri?eid=2...,Chevalier P.; Floris F.; Priolo T.; De Tommaso...,Lecture Notes in Computer Science (including s...,2021.0,Scopus,Title: “iCub Says: Do My Motor Sounds Disturb ...

In [ ]:
df

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year,Database,text
0,"""Mommy Blogs"" and the Vaccination Exemption Na...",Social media offer an unprecedented opportunit...,"['Internet', 'attitudes', 'health knowledge', ...",10.2196/publichealth.6586,https://pubmed.ncbi.nlm.nih.gov/27876690/,"Tangherlini, Roychowdhury, Glenn, Crespi, Band...",JMIR public health and surveillance,2016.0,PubMed,"Title: ""Mommy Blogs"" and the Vaccination Exemp..."
1,"""Sequencing Matters"": Investigating Suitable A...",Social robots have been shown to be promising ...,"['action selection', 'attention skills', 'auti...",10.3389/frobt.2022.784249,https://pubmed.ncbi.nlm.nih.gov/35356059/,"Baraka, Couto, Melo, Paiva, Veloso",Frontiers in robotics and AI,2022.0,PubMed,"Title: ""Sequencing Matters"": Investigating Sui..."
2,"""Um"" and ""Uh"" Usage Patterns in Children with ...","Pragmatic language difficulties, including unu...","['Autism', 'Disfluency', 'Fillers', 'Natural l...",10.1007/s10803-022-05565-4,https://pubmed.ncbi.nlm.nih.gov/35499654/,"Lawley, Bedrick, MacFarlane, Dolata, Salem, Fo...",Journal of autism and developmental disorders,2023.0,PubMed,"Title: ""Um"" and ""Uh"" Usage Patterns in Childre..."
3,'SenseA'-Autism Early Signs and Pre-Aggressive...,This paper presents an efficient solution for ...,autism early signs; computer vision; feature e...,10.1109/AMS.2017.28,https://www.scopus.com/inward/record.uri?eid=2...,Gamaethige C.; Gunathilake U.; Jayasena D.; Ma...,AMS 2017 - Asia Modelling Symposium 2017 and 1...,2018.0,Scopus,Title: 'SenseA'-Autism Early Signs and Pre-Agg...
4,25th Annual Computational Neuroscience Meeting...,A1 Functional advantages of cell-type heteroge...,NaN,10.1186/s12868-016-0283-6,https://pubmed.ncbi.nlm.nih.gov/27534393/,NaN,BMC neuroscience,2016.0,PubMed,Title: 25th Annual Computational Neuroscience ...
...,...,...,...,...,...,...,...,...,...,...
1832,rs-fMRI Analysis Using Spatio-Temporal Sparse ...,Neuropsychiatric diseases such as Autism Spect...,CNN; Deep Learning; fMRI; Image Processing; Su...,10.1109/SIU55565.2022.9864751,https://www.scopus.com/inward/record.uri?eid=2...,Yener F.M.; Yildiz S.; Hafeez M.A.; Kayasandik...,2022 30th Signal Processing and Communications...,2022.0,Scopus,Title: rs-fMRI Analysis Using Spatio-Temporal ...
1833,rs-fMRI and machine learning for ASD diagnosis...,Autism Spectrum Disorder (ASD) diagnosis is st...,NaN,10.1038/s41598-022-09821-6,https://pubmed.ncbi.nlm.nih.gov/35411059/,"Santana, de Carvalho, Rodrigues, Bastos, de So...",Scientific reports,2022.0,PubMed,Title: rs-fMRI and machine learning for ASD di...
1834,sha-Early Intervention for children at risk of...,Autism Spectrum Disorder (ASD) is a developmen...,Autism Spectrum Disorder; CNN; Cognitive devel...,10.1109/I4Tech55392.2022.9952803,https://www.scopus.com/inward/record.uri?eid=2...,Shetty T.; Zope V.; Dandekar M.; Devnani A.; M...,2022 International Conference on Industry 4.0 ...,2022.0,Scopus,Title: sha-Early Intervention for children at ...
1835,‘Autistic Robots’ for Embodied Emulation of Be...,The goal of this work is to enable interaction...,NaN,10.1007/978-3-319-70022-9_11,https://www.scopus.com/inward/record.uri?eid=2...,Baraka K.; Melo F.S.; Veloso M.,Lecture Notes in Computer Science (including s...,2017.0,Scopus,Title: ‘Autistic Robots’ for Embodied Emulatio...
1836,“iCub Says: Do My Motor Sounds Disturb You?” M...,"In Socially Assistive Robotics, robots are use...",Auditory sensitivity; Autism spectrum disorder...,10.1007/978-3-030-90525-5_56,https://www.scopus.com/inward/record.uri?eid=2...,Chevalier P.; Floris F.; Priolo T.; De Tommaso...,Lecture Notes in Computer Science (including s...,2021.0,Scopus,Title: “iCub Says: Do My Motor Sounds Disturb ...

In [ ]:
if 'Overall' not in df.columns:
    df['Overall'] = None

for index, row in df.iterrows():
    if index % 100 == 0:
        print(index)
    if row["Overall"] is None:
        title = row['Title']
        abstract = row['Abstract']
        keywords = row['Keywords']
        doi = row['DOI']
        url = row['URL']
        authors = row['Authors']
        venue = row['Venue']
        year = row['Year']
        database = row['Database']

        # Now you can process or print the title, abstract, and keywords for each row
        #print(f'Title: {title}\nAbstract: {abstract}\nKeywords: {keywords}\n')
        extra_message = {
          "role": "user",
          "content": f"Title: {title} \nAbstract: {abstract}  \Keywords: {keywords}"
        }
        messages = examples.copy()
        messages.append(extra_message)
        #print(len(messages))

        try:
            response = openai.ChatCompletion.create(
                engine="attempt1",
                messages = messages,
                temperature=0.5,
                max_tokens=700,
                top_p=0.5,
                frequency_penalty=0,
                presence_penalty=0,
                stop=None
            )

            my_response = response['choices'][0]['message']['content']
            #print(my_response)

            try:
                my_response_dict = json.loads(my_response)
                # Now you can access each field by its key and assign it to a variable:
                field_1 = my_response_dict["1"]
                if not field_1:
                    print(f'Title: {title}\nAbstract: {abstract}\nKeywords: {keywords}\n')
                '''
                field_2 = my_response_dict["2"]
                field_3 = my_response_dict["3"]
                field_4 = my_response_dict["4"]
                field_5 = my_response_dict["5"]
                field_6 = my_response_dict["6"]
                field_7 = my_response_dict["7"]
                field_8 = my_response_dict["8"]
                field_9 = my_response_dict["9"]
                field_10 = my_response_dict["10"]
                '''
                rational = my_response_dict["rational"]

                df.loc[index, "English?"] = field_1
                '''
                df.loc[index, "Empirical study?"] = not field_2 and field_10
                df.loc[index, "Human participants?"] = field_3 and not field_4
                df.loc[index, "Participants with (suspected) ASD included?"] = field_5
                df.loc[index, "Is autism diagnosis the focus?"] = field_6
                df.loc[index, "AI used?"] = field_7
                df.loc[index, "Behavioral data used?"] = field_8
                df.loc[index, "Are participants children?"] = field_9
                df.loc[index, "Overall"] = None
                '''
                df.loc[index, "Notes"] = rational
            except Exception as e:
                df.loc[index, "Notes"] = my_response
                print(f"There was a json management error with index {index}")
                #print(f"Error: {e}")
                #print(response)
        except Exception as e:
            print(f"There was an error with index {index}")
            print(f"Error: {e}")
            #print(response)
            #input("AA")

0
100
200
300
Title: Atypical gaze patterns in autistic adults are heterogeneous across but reliable within individuals.
Abstract: Across behavioral studies, autistic individuals show greater variability than typically developing individuals. However, it remains unknown to what extent this variability arises from heterogeneity across individuals, or from unreliability within individuals. Here, we focus on eye tracking, which provides rich dependent measures that have been used extensively in studies of autism. Autistic individuals have an atypical gaze onto both static visual images and dynamic videos that could be leveraged for diagnostic purposes if the above open question could be addressed.We tested three competing hypotheses: (1) that gaze patterns of autistic individuals are less reliable or noisier than those of controls, (2) that atypical gaze patterns are individually reliable but heterogeneous across autistic individuals, or (3) that atypical gaze patterns are individually reliable and also homogeneous among autistic individuals. We collected desktop-based eye tracking data from two different full-length television sitcom episodes, at two independent sites (Caltech and Indiana University), in a total of over 150 adult participants (N = 48 autistic individuals with IQ in the normal range, 105 controls) and quantified gaze onto features of the videos using automated computer vision-based feature extraction.We found support for the second of these hypotheses. Autistic people and controls showed equivalently reliable gaze onto specific features of videos, such as faces, so much so that individuals could be identified significantly above chance using a fingerprinting approach from video epochs as short as 2 min. However, classification of participants into diagnostic groups based on their eye tracking data failed to produce clear group classifications, due to heterogeneity in the autistic group.Three limitations are the relatively small sample size, assessment across only two videos (from the same television series), and the absence of other dependent measures (e.g., neuroimaging or genetics) that might have revealed individual-level variability that was not evident with eye tracking. Future studies should expand to larger samples across longer longitudinal epochs, an aim that is now becoming feasible with Internet- and phone-based eye tracking.These findings pave the way for the investigation of autism subtypes, and for elucidating the specific visual features that best discriminate gaze patterns-directions that will also combine with and inform neuroimaging and genetic studies of this complex disorder.
Keywords: ['Autism', 'Eye tracking', 'Heterogeneity', 'Individual differences', 'Videos']

Title: Author Correction: Atypical postural control can be detected via computer vision analysis in toddlers with autism spectrum disorder.
Abstract: An amendment to this paper has been published and can be accessed via a link at the top of the paper. [ABSTRACT FROM AUTHOR], Copyright of Scientific Reports is the property of Springer Nature and its content may not be copied or emailed to multiple sites or posted to a listserv without the copyright holder's express written permission. However, users may print, download, or email articles for individual use. This abstract may be abridged. No warranty is given about the accuracy of the copy. Users should refer to the original published version of the material for the full abstract. (Copyright applies to all Abstracts.)
Keywords: AUTISM spectrum disorders, MOTOR ability

400
500
600
Title: Correction to: A Systematic Review of Familiarisation Methods Used in Human–Robot Interactions for Autistic Participants (International Journal of Social Robotics, (2023), 10.1007/s12369-023-01015-y)
Abstract: Correction to: International Journal of Social Robotics In the above-mentioned paper, Table 3 was incorrectly published. Please find the correct Table 3 below. (Table presented.) The summary of the included studies in the systematic review Citation Age of participants (years) Diagnosis Robot Categorised familiarisation type [2] 6–7 ASD NAO Capability demonstration [3] 9 ASD via DSM 5 ARC Initial experimental session [4] Child—age not specified No detail NAO Static exploration, stimulus and response [7] 7–11 ASD KiliRo Static exploration [8] 3–6 ASD w/ speech impairment or language delay CHARLIE Static exploration, remote control [10] 5–16 ASD TeoG Static exploration, free play [11] 4–6 ASD via DSM-IV NAO Free play: elements of capability demonstration & stimulus and response [12] Child—age not specified ASD PLEO Free play [16] 17–19 ASD LEGO MindStorms NTX Initial experimental session, capability demonstration [18] 5 ASD NAO & MiRo Capability demonstration [20] 5–11 ASD via ADOS Gipy Capability demonstration [21] 7–12 ASD, no ID Daisy robot Capability demonstration, stimulus and response, element of static exploration [24] 6–7 ASD via DSM-IV Pekoppa Capability demonstration [25] 6–7 ASD via DSM-IV Pekoppa Capability demonstration [26] 7–11 ASD via DSM-V Pekoppa Capability demonstration [27] 2–5 No detail QueBall Capability demonstration, stimulus and response [28] 7–11 ASD MARIA Capability demonstration [29] 8–12 ASD, severe to mild ID KASPAR Capability demonstration, stimulus and response [30] 8–12 ASD via DSM-IV, no ID NAO Capability demonstration [31] Child—age not specified No detail NAO Static exploration, capability demonstration [33] 2–6 PDD-NOS or Autism iRobi Static exploration [34] 4–5 ASD, low to high functioning CuDDler Initial experimental session [35] 7–11 ASD via DSM-IV, low to high functioning KASPAR Static exploration [36] 5 ASD via DSM-V NAO Stimulus and response [37] 5–10 ASD, severe ID White, spherical prototype Static exploration [40] 18–27 ASD via DSM-V, DISCO Actroid-F Remote control [49] 4–5 ASD via DSM-V NAO Initial experimental session [50] 7–9 ASD NAO Stimulus and response [51] 6–9 ASD NAO Stimulus and response [55] 1–5 ASD NAO Capability demonstration [56] 7–9 ASD, low severity Daisy robot Initial experimental session [57] 4–9 ASD via ADOS & DSM-IV Probo Stimulus and response, capability demonstration [59] 7–11 ASD NAO Initial experimental session [62] 5–10 ASD, verbal and non-verbal children Robota Capability demonstration [63] 5 ASD Robota Capability demonstration, initial experimental session [64] 5–10 ASD, verbal and non-verbal children Robota Capability demonstration [65] Child—age not specified ASD Robota Initial experimental session [66] 5–10 ASD, verbal and non-verbal children Robota Capability demonstration [67] Child—age not specified No detail KASPAR Free play [68] 6–8 ASD via CARS, ADOS NAO Capability demonstration, static exploration [69] 5–12 ASD via ICD-10, DSM-IV or DSM-V Zeno/Milo Capability demonstration [71] 5–13 ASD via ADOS, moderate to borderline ID NAO Capability demonstration [72] 5–9 ASD via ADOS/ADI Humanoid robot, box robot Capability demonstration [73] 5–7 ASD, no ID Probo Free play: elements of capability demonstration, stimulus and response & Static exploration [75] 3–5 ASD via CARS RoboParrot & Sphero Stimulus and response [76] 2–6 5 with ASD via DSM-IV, 1 suspected ASD NAO Stimulus and response [77] 59–70 ASD w/ ID Robot seal Paro Static exploration [80] 8–12 ASD, high functioning or Asperger’s syndrome 2 robots A and B, make unknown Static exploration [81] 5–8 ASD via DSM-IV, ADOS/ADI/SRS NAO Stimulus and response [82] 5–8 ASD via DSM-IV & ADOS/ADI NAO Stimulus and response DSM diagnostic and statistical manual of mental disorders [14], ID intellectual disability, ADOS autism diagnostic observation schedule [46], PDD-NOS pervasive developmental disorder - not otherwise specified, DISCO diagnostic interview for social and communication disorders [43, 79], CARS childhood autism rating scale [70], ICD-10 international classification of diseases (World Health Organisation), ADI autism diagnostic interview [47], SRS social responsiveness scale [13] Springer wishes to apologize for any inconvenience caused. © 2023, Springer Nature B.V.
Keywords: nan

700
800
900
1000
1100
1200
Title: ML Algorithms that have been Utilised to Classify Neuro-Developmental Disorders: A Review
Abstract: The Autism Diagnostic Interview (ADI)-revised is frequently used to aid in the repetitive behaviors that are unusual recognition of autism. Heredity and environment both have an impact on the emergence of neuro-developmental diseases like Autism Spectrum Disorder (ASD). For diagnosing ASDs, conventional clinical evaluations from the last few decades are still often used. These traditional methods rely on gathering a lot of information from the responses of many respondents and the severity of different behavioural features, which is then recognised by the researcher when constructing a diagnostic criterion. On the other hand, traditional diagnostic techniques have a high risk of generating an inaccurate diagnosis, which could lead to the unwarranted recommendation of long-lasting medicinal therapy. This could lead to a decline in functioning and a higher chance of developing other clinical and social issues. The focus of this work is on the implementation of Machine Learning (ML) technologies for the immediate treatment and identificaton of ASD symptoms. Despite the fact that many studies have been carried out, we still think that our review paper is pertinent and can help those researchers who are working on this subject by providing all they require in one location. . © 2023 IEEE.
Keywords: Artificial Intelligence; Autism; Autism Diagnostic Interview-Revised; Autism Spectrum Disorder; Neuro Developmental Disorder; Support Vector Machine

Title: Machine learning techniques for healthcare applications: Early autism detection using ensemble approach and breast cancer prediction using smo and IBK
Abstract: Autism spectrum disorder (ASD) is one of the common disorders in brain. Early detection of ASD improves the overall mental health, which is very important for the future of the child. ASD affects social coordination, emotions, and motor activity of an individual. This is due to the difficulties in getting selfevaluation results and expressive experiences. In the first case study in this chapter, an efficient method to automatically detect the expressive states of individuals with the help of physiological signals is explored. In the second case study of the chapter, the authors explore breast cancer prediction using SMO and IBK. Breast cancer is the second leading cause of cancer deaths in women worldwide and occurs in nearly one out of eight. In this proposed system, the tumor is the feature that is used to identify the breast cancer presence in women. Tumors are basically of two types (i.e., benign or malignant). In order to provide appropriate treatment to the patients, symptoms must be studied properly, and an automatic prediction system is required that will classify the tumor into benign or malignant using SMO and IBK. © 2023, IGI Global. All rights reserved.
Keywords: nan

1300
1400
Title: Review of Progress in Diagnostic Studies of Autism Spectrum Disorder Using Neuroimaging.
Abstract: This review article summarizes the recent advances in the diagnostic studies of autism spectrum disorders (ASDs) considering some of the most influential research articles from the last two decades. ASD is a heterogeneous neurodevelopmental disorder characterized by abnormalities in social interaction, communication, and behavioral patterns as well as some unique strengths and differences. The current diagnosis systems are based on autism diagnostic observation schedule (ADOS) or autism diagnostic interview-revised (ADI-R), but biological markers are also important for an effective diagnosis of ASDs. The amalgamation of neuroimaging techniques, such as structural and functional magnetic resonance imaging (sMRI and fMRI), with machine-learning and deep-learning approaches helps throw new light on typical biological markers of ASDs at the early stage of life. To assess the performance of a deep neural network, we develop a light-weighted CNN model for ASD classification. The overall accuracy, precision, and F1-score of the proposed model are 99.92%, 99.93% and 99.92%, respectively. All the neuroimaging studies we have reviewed can be divided into 3 categories, viz. thickness, volume and functional connectivity-based studies. We conclude with a discussion of the major findings of considered studies and promising directions for future research in this field.
Keywords: ['Autism spectrum disorders', 'Functional magnetic resonance imaging', 'Machine-learning', 'Neurodevelopmental disorder', 'Structural magnetic resonance imaging']

1500
1600
1700
Title: Understanding children with autism spectrum disorders
Abstract: Understanding Children with Autism Spectrum Disorders first discusses auditory processing disorders are, specifically how auditory processing problems can affect children with autism spectrum disorders, and appropriate evidence-based treatments. The authors highlight the challenges associated with making a dual diagnosis, and discuss specific anatomical differences in the central auditory pathway and brain. Also highlighted is the need for improved research on intervention programs and the important service needs for families and children with autism spectrum disorders. A study is presented wherein pediatric volition among children with autism spectrum disorders participating in the Holland Bloorview (HB) FIRST® robotics program is measured. A review is carried out in order to describe the main neurotransmitters in autism spectrum condition patients. Among the studied neurotransmitters, increased serotonin and glutamate as well as decreased levels of gamma-aminobutyric acid N-Acetylaspartate and oxytocin appear to have the most empirical evidence. The authors assess the relationship between autism spectrum disorder symptomatology, theory of mind, and other individual factor on children's responses through a study attempting to determine the factors that contribute to the complexity of the emotion of embarrassment. The closing study addresses that with respect to dietary issues, awareness of the eating habits and feeding problems experienced by autism spectrum disorder children needs to be emphasized among parents and guardians. © 2020 by Nova Science Publishers, Inc. All rights reserved.
Keywords: nan

1800

In [ ]:
df

,Title,Abstract,Keywords,DOI,URL,Authors,Venue,Year,Database,text,Overall,English?,Notes
0,"""Mommy Blogs"" and the Vaccination Exemption Na...",Social media offer an unprecedented opportunit...,"['Internet', 'attitudes', 'health knowledge', ...",10.2196/publichealth.6586,https://pubmed.ncbi.nlm.nih.gov/27876690/,"Tangherlini, Roychowdhury, Glenn, Crespi, Band...",JMIR public health and surveillance,2016.0,PubMed,"Title: ""Mommy Blogs"" and the Vaccination Exemp...",None,True,The paper's title and abstract are written in ...
1,"""Sequencing Matters"": Investigating Suitable A...",Social robots have been shown to be promising ...,"['action selection', 'attention skills', 'auti...",10.3389/frobt.2022.784249,https://pubmed.ncbi.nlm.nih.gov/35356059/,"Baraka, Couto, Melo, Paiva, Veloso",Frontiers in robotics and AI,2022.0,PubMed,"Title: ""Sequencing Matters"": Investigating Sui...",None,True,The paper's title and abstract are written in ...
2,"""Um"" and ""Uh"" Usage Patterns in Children with ...","Pragmatic language difficulties, including unu...","['Autism', 'Disfluency', 'Fillers', 'Natural l...",10.1007/s10803-022-05565-4,https://pubmed.ncbi.nlm.nih.gov/35499654/,"Lawley, Bedrick, MacFarlane, Dolata, Salem, Fo...",Journal of autism and developmental disorders,2023.0,PubMed,"Title: ""Um"" and ""Uh"" Usage Patterns in Childre...",None,True,The title and abstract are written in English.
3,'SenseA'-Autism Early Signs and Pre-Aggressive...,This paper presents an efficient solution for ...,autism early signs; computer vision; feature e...,10.1109/AMS.2017.28,https://www.scopus.com/inward/record.uri?eid=2...,Gamaethige C.; Gunathilake U.; Jayasena D.; Ma...,AMS 2017 - Asia Modelling Symposium 2017 and 1...,2018.0,Scopus,Title: 'SenseA'-Autism Early Signs and Pre-Agg...,None,True,The title and abstract are written in English.
4,25th Annual Computational Neuroscience Meeting...,A1 Functional advantages of cell-type heteroge...,NaN,10.1186/s12868-016-0283-6,https://pubmed.ncbi.nlm.nih.gov/27534393/,NaN,BMC neuroscience,2016.0,PubMed,Title: 25th Annual Computational Neuroscience ...,None,True,The paper's title and abstract are written in ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1832,rs-fMRI Analysis Using Spatio-Temporal Sparse ...,Neuropsychiatric diseases such as Autism Spect...,CNN; Deep Learning; fMRI; Image Processing; Su...,10.1109/SIU55565.2022.9864751,https://www.scopus.com/inward/record.uri?eid=2...,Yener F.M.; Yildiz S.; Hafeez M.A.; Kayasandik...,2022 30th Signal Processing and Communications...,2022.0,Scopus,Title: rs-fMRI Analysis Using Spatio-Temporal ...,None,True,The paper's title and abstract are written in ...
1833,rs-fMRI and machine learning for ASD diagnosis...,Autism Spectrum Disorder (ASD) diagnosis is st...,NaN,10.1038/s41598-022-09821-6,https://pubmed.ncbi.nlm.nih.gov/35411059/,"Santana, de Carvalho, Rodrigues, Bastos, de So...",Scientific reports,2022.0,PubMed,Title: rs-fMRI and machine learning for ASD di...,None,True,The title and abstract are written in English.
1834,sha-Early Intervention for children at risk of...,Autism Spectrum Disorder (ASD) is a developmen...,Autism Spectrum Disorder; CNN; Cognitive devel...,10.1109/I4Tech55392.2022.9952803,https://www.scopus.com/inward/record.uri?eid=2...,Shetty T.; Zope V.; Dandekar M.; Devnani A.; M...,2022 International Conference on Industry 4.0 ...,2022.0,Scopus,Title: sha-Early Intervention for children at ...,None,True,The paper's title and abstract are written in ...
1835,‘Autistic Robots’ for Embodied Emulation of Be...,The goal of this work is to enable interaction...,NaN,10.1007/978-3-319-70022-9_11,https://www.scopus.com/inward/record.uri?eid=2...,Baraka K.; Melo F.S.; Veloso M.,Lecture Notes in Computer Science (including s...,2017.0,Scopus,Title: ‘Autistic Robots’ for Embodied Emulatio...,None,True,The title and abstract are written in English.
1836,“iCub Says: Do My Motor Sounds Disturb You?” M...,"In Socially Assistive Robotics, robots are use...",Auditory sensitivity; Autism spectrum disorder...,10.1007/978-3-030-90525-5_56,https://www.scopus.com/inward/record.uri?eid=2...,Chevalier P.; Floris F.; Priolo T.; De Tommaso...,Lecture Notes in Computer Science (including s...,2021.0,Scopus,Title: “iCub Says: Do My Motor Sounds Disturb ...,None,True,The paper's title and abstract are written in ...

In [ ]:
df.to_csv(f'{main_folder}/autism_ai_behavior_diagnosis_formatted__controlled_combined_noduplicates_semanticallyfiltered_FABIO_RAW.csv', index=False)

In [ ]:
		"content": "Title: Machine Learning for Differential Diagnosis Between Clinical Conditions With Social Difficulty: Autism Spectrum Disorder, Early Psychosis, and Social Anxiety Disorder.  \nAbstract: Differential diagnosis in adult cohorts with social difficulty is confounded by comorbid mental health conditions, common etiologies, and shared phenotypes. Identifying shared and discriminating profiles can facilitate intervention and remediation strategies. The objective of the study was to identify salient features of a composite test battery of cognitive and mood measures using a machine learning paradigm in clinical cohorts with social interaction difficulties. We recruited clinical participants who met standardized diagnostic criteria for autism spectrum disorder (ASD: n = 62), early psychosis (EP: n = 48), or social anxiety disorder (SAD: N = 83) and compared them with a neurotypical comparison group (TYP: N = 43). Using five machine-learning algorithms and repeated cross-validation, we trained and tested classification models using measures of cognitive and executive function, lower- and higher-order social cognition and mood severity. Performance metrics were the area under the curve (AUC) and Brier Scores. Sixteen features successfully differentiated between the groups. The control versus social impairment cohorts (ASD, EP, SAD) were differentiated by social cognition, visuospatial memory and mood measures. Importantly, a distinct profile cluster drawn from social cognition, visual learning, executive function and mood, distinguished the neurodevelopmental cohort (EP and ASD) from the SAD group. The mean AUC range was between 0.891 and 0.916 for social impairment versus control cohorts and, 0.729 to 0.781 for SAD vs neurodevelopmental cohorts. This is the first study that compares an extensive battery of neuropsychological and self-report measures using a machine learning protocol in clinical and neurodevelopmental cohorts characterized by social impairment. Findings are relevant for diagnostic, intervention and remediation strategies for these groups.  \Keywords: ['autism spectrum disorder', 'cognition', 'differential diagnosis', 'early psychosis', 'machine learning', 'social anxiety disorder']"

In [ ]:
title = "Machine Learning for Differential Diagnosis Between Clinical Conditions With Social Difficulty: Autism Spectrum Disorder, Early Psychosis, and Social Anxiety Disorder."
abstract = "Differential diagnosis in adult cohorts with social difficulty is confounded by comorbid mental health conditions, common etiologies, and shared phenotypes. Identifying shared and discriminating profiles can facilitate intervention and remediation strategies. The objective of the study was to identify salient features of a composite test battery of cognitive and mood measures using a machine learning paradigm in clinical cohorts with social interaction difficulties. We recruited clinical participants who met standardized diagnostic criteria for autism spectrum disorder (ASD: n = 62), early psychosis (EP: n = 48), or social anxiety disorder (SAD: N = 83) and compared them with a neurotypical comparison group (TYP: N = 43). Using five machine-learning algorithms and repeated cross-validation, we trained and tested classification models using measures of cognitive and executive function, lower- and higher-order social cognition and mood severity. Performance metrics were the area under the curve (AUC) and Brier Scores. Sixteen features successfully differentiated between the groups. The control versus social impairment cohorts (ASD, EP, SAD) were differentiated by social cognition, visuospatial memory and mood measures. Importantly, a distinct profile cluster drawn from social cognition, visual learning, executive function and mood, distinguished the neurodevelopmental cohort (EP and ASD) from the SAD group. The mean AUC range was between 0.891 and 0.916 for social impairment versus control cohorts and, 0.729 to 0.781 for SAD vs neurodevelopmental cohorts. This is the first study that compares an extensive battery of neuropsychological and self-report measures using a machine learning protocol in clinical and neurodevelopmental cohorts characterized by social impairment. Findings are relevant for diagnostic, intervention and remediation strategies for these groups."
keywords = "['autism spectrum disorder', 'cognition', 'differential diagnosis', 'early psychosis', 'machine learning', 'social anxiety disorder']"
extra_message = {
		"role": "user",
		"content": f"Title: {title} \nAbstract: {abstract}  \Keywords: {keywords}"
	}

In [ ]:
messages = examples
messages.insert(0, extra_message)
messages

[{'role': 'user',
  'content': "Title: Machine Learning for Differential Diagnosis Between Clinical Conditions With Social Difficulty: Autism Spectrum Disorder, Early Psychosis, and Social Anxiety Disorder. \nAbstract: Differential diagnosis in adult cohorts with social difficulty is confounded by comorbid mental health conditions, common etiologies, and shared phenotypes. Identifying shared and discriminating profiles can facilitate intervention and remediation strategies. The objective of the study was to identify salient features of a composite test battery of cognitive and mood measures using a machine learning paradigm in clinical cohorts with social interaction difficulties. We recruited clinical participants who met standardized diagnostic criteria for autism spectrum disorder (ASD: n = 62), early psychosis (EP: n = 48), or social anxiety disorder (SAD: N = 83) and compared them with a neurotypical comparison group (TYP: N = 43). Using five machine-learning algorithms and repeated cross-validation, we trained and tested classification models using measures of cognitive and executive function, lower- and higher-order social cognition and mood severity. Performance metrics were the area under the curve (AUC) and Brier Scores. Sixteen features successfully differentiated between the groups. The control versus social impairment cohorts (ASD, EP, SAD) were differentiated by social cognition, visuospatial memory and mood measures. Importantly, a distinct profile cluster drawn from social cognition, visual learning, executive function and mood, distinguished the neurodevelopmental cohort (EP and ASD) from the SAD group. The mean AUC range was between 0.891 and 0.916 for social impairment versus control cohorts and, 0.729 to 0.781 for SAD vs neurodevelopmental cohorts. This is the first study that compares an extensive battery of neuropsychological and self-report measures using a machine learning protocol in clinical and neurodevelopmental cohorts characterized by social impairment. Findings are relevant for diagnostic, intervention and remediation strategies for these groups.  \\Keywords: ['autism spectrum disorder', 'cognition', 'differential diagnosis', 'early psychosis', 'machine learning', 'social anxiety disorder']"},
 {'role': 'system',
  'content': '\n      Reply with true or false: \n      1- The paper is in English.\n      2- The paper is a position paper and primarily focus on opinion or argumentation.\n      3- The paper is a literature review.\n      4- The study does recruit at least one participant.\n      5- The study involves animals as participants.\n      6- In the study there are some participants who have autism or are suspected to have autism.\n      7- The paper does address assessment, screening, diagnosis, prediction, or detection of autism, and not only training/therapy/treatment.\n      8- The study does involve the application of artificial intelligence (AI).\n      9- The study makes use of behavioral data (e.g., gaze, movements, posture, facial expressions, voice and speech, play, social interaction, and emotions).\n      \n      Use the following JSON template:\n{"1": true/false, ..., "rational": "<TEXT WITH MOTIVATIONS FOR YOUR RESPONSES. ONE SENTECE FOR EACH BULLET POINT."}\n      '}]

In [ ]:
response = openai.ChatCompletion.create(
  engine="attempt1",
  messages = messages,
  temperature=0.6,
  max_tokens=700,
  top_p=0.95,
  frequency_penalty=0,
  presence_penalty=0,
  stop=None)

In [ ]:
my_response = response['choices'][0]['message']['content']
my_response

'{\n"1": true,\n"2": false,\n"3": false,\n"4": true,\n"5": false,\n"6": true,\n"7": true,\n"8": true,\n"9": true,\n"rational": "The paper is written in English and reports a scientific study involving machine learning algorithms and neuropsychological measures. It is not a position paper or a literature review. The study does recruit participants with autism spectrum disorder, early psychosis, social anxiety disorder and a neurotypical comparison group. The study does not involve animals. The paper does address assessment and diagnosis of autism, as well as other social impairment conditions. The study involves the application of artificial intelligence and uses behavioral data to differentiate between clinical cohorts."\n}'

In [ ]:
1- The paper is in English. OK
2- The paper is a position paper explicitly mentions the design, execution, or results of an empirical investigation, and does not primarily focus on opinion, argumentation, or solely summarizing existing literature.
OK
3- The paper is a literature review. (PUO' SALTARE???)
4- The paper does involve at least one participant.
5- The study involves animals as participants.
6- In the study there are some participants who have autism or are suspected to have autism.
7- The paper does address assessment, screening, diagnosis, prediction, or detection of autism, and not only training/therapy/treatment.
8- The study does involve the application of artificial intelligence (AI).
9- The study makes use of behavioral data (e.g., gaze, movements, posture, facial expressions, voice and speech, play, social interaction, and emotions).
 {
  "role": "assistant",
  "content": "{1: true, 2: false, 3: false, 4: false, 5: true, 6: true, 7: false, \"rational\":\nThe paper is in English (1) and is not an empirical study (it's a literature review) (2). The study does not involve humans (3). The paper does not include participants diagnosed with ASD or suspected to have ASD (4) but directly addresses the assessment/screening/diagnosis of autism (5). The study involves the application of artificial intelligence (AI) (6) but does not make use of behavioral data (7).}"
},
1- The paper is not in English.\n2- The paper is not about empirical experimentation.\n3- The study doesn't involve human participants.\n4- The study does not include participants (at least) suspected to have autism.\n5- The paper does not address assessment, screening, diagnosis, prediction, or detection of autism.\n6- The study does not involve the application of artificial intelligence (AI).\n7- The study makes use of behavioral data (e.g., gaze, movements, posture, facial expressions, voice and speech, play, social interaction, and emotions).

In [ ]:
my_response

'{"1": true, "2": true, "3": false, "4": true, "5": true, "6": true, "7": true, "rational": "The paper is in English (1) and is an empirical study (2). The study does not involve animal subjects or computational simulations and includes human participants (4). The paper directly addresses the assessment, screening, diagnosis, or detection of autism (5) and involves the application of artificial intelligence (AI) through the use of facial expression detection (6) and the use of behavioral data in the form of emotional and social interactions (7)."}'

In [ ]:
my_response = response['choices'][0]['message']['content']

# Parse the JSON string into a dictionary:
my_response_dict = json.loads(my_response)

# Now you can access each field by its key and assign it to a variable:
field_1 = my_response_dict["1"]
field_2 = my_response_dict["2"]
field_3 = my_response_dict["3"]
field_4 = my_response_dict["4"]
field_5 = my_response_dict["5"]
field_6 = my_response_dict["6"]
field_7 = my_response_dict["7"]
rational = my_response_dict["rational"]

result = [field_1, field_2, field_3, field_4, field_5, field_6, field_7, rational]

In [ ]:
rational

'The paper is in English (1) and is an empirical study (2). The study does not involve animal subjects or computational simulations and includes human participants (4). The paper directly addresses the assessment, screening, diagnosis, or detection of autism (5) and involves the application of artificial intelligence (AI) through the use of facial expression detection (6) and the use of behavioral data in the form of emotional and social interactions (7).'

In [ ]:
response

<OpenAIObject chat.completion id=chatcmpl-86N4qnpljb71cikG3rgSzTrCSKwB7 at 0x7e1a99ee4450> JSON: {
  "id": "chatcmpl-86N4qnpljb71cikG3rgSzTrCSKwB7",
  "object": "chat.completion",
  "created": 1696529368,
  "model": "gpt-35-turbo",
  "prompt_annotations": [
    {
      "prompt_index": 0,
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ],
  "choices": [
    {
      "index": 0,
      "finish_reason": "stop",
      "message": {
        "role": "assistant",
        "content": "{1: True, 2: True, 3: False, 4: True, 5: True, 6: True, 7: True, \"rational\":\nThe paper is in English (1) and is an empirical study (2). The study does not involve animal subjects or human participants (3) but includes participants diagnosed with ASD (4) and directly addresses the treatment of autism through the use of assistive robotics and sonification (5). The study involves the application of artificial intelligence (AI) through the development of a facial expression detection system (6) and makes use of behavioral data in the form of emotional and social interactions (7).}"
      },
      "content_filter_results": {
        "hate": {
          "filtered": false,
          "severity": "safe"
        },
        "self_harm": {
          "filtered": false,
          "severity": "safe"
        },
        "sexual": {
          "filtered": false,
          "severity": "safe"
        },
        "violence": {
          "filtered": false,
          "severity": "safe"
        }
      }
    }
  ],
  "usage": {
    "completion_tokens": 138,
    "prompt_tokens": 4411,
    "total_tokens": 4549
  }
}